Copy the external libraries into the install tree.  This is the first step in making the hpctoolkit install be self-contained, so it won't need the externals tree at run time.  Hpclink and maybe hpcrun can now run without the externals tree.
Add the shell code snipit file export-hpctoolkit as a uniform way for
a script to find its install prefix and set HPCTOOLKIT environment
variable.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -898,18 +898,28 @@ HOST_HPCPROF_LDFLAGS
 HOST_HPCPROF_FLAT_LDFLAGS
 HOST_HPCPROFTT_LDFLAGS
 HOST_XPROF_LDFLAGS
+hpc_ext_libs_dir
 LIBDWARF_LIB
+LIBDWARF_COPY
 LIBELF_LIB
+LIBELF_COPY
 LIBMONITOR_INC
 LIBMONITOR_LIB
-libmonitor_prefix
+LIBMONITOR_COPY
+LIBMONITOR_RUN_DIR
 SYMTABAPI_INC
 SYMTABAPI_LIB
+SYMTABAPI_COPY
+SYMTABAPI_RUN_DIR
 XED2_INC
 XED2_LIB
+XED2_COPY
+XED2_RUN_DIR
 XERCES
 XERCES_IFLAGS
 XERCES_LDFLAGS
+XERCES_COPY
+XERCES_LIB
 OA_IFLAGS
 OA_LDFLAGS
 GNUBINUTILS_IFLAGS
@@ -948,7 +958,7 @@ OPT_ENABLE_LUSH_FALSE
 OPT_OBJCOPY
 LIBOBJS
 LTLIBOBJS'
-ac_subst_files=''
+ac_subst_files='export_hpctoolkit'
       ac_precious_vars='build_alias
 host_alias
 target_alias
@@ -4518,7 +4528,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4521 "configure"' > conftest.$ac_ext
+  echo '#line 4531 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7575,11 +7585,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7578: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7588: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7582: \$? = $ac_status" >&5
+   echo "$as_me:7592: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7865,11 +7875,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7868: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7878: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7872: \$? = $ac_status" >&5
+   echo "$as_me:7882: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7969,11 +7979,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7972: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7982: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7976: \$? = $ac_status" >&5
+   echo "$as_me:7986: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10333,7 +10343,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10336 "configure"
+#line 10346 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10433,7 +10443,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10436 "configure"
+#line 10446 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12834,11 +12844,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12837: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12847: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12841: \$? = $ac_status" >&5
+   echo "$as_me:12851: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12938,11 +12948,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12941: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12951: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12945: \$? = $ac_status" >&5
+   echo "$as_me:12955: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14521,11 +14531,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14524: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14534: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14528: \$? = $ac_status" >&5
+   echo "$as_me:14538: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14625,11 +14635,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14628: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14638: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14632: \$? = $ac_status" >&5
+   echo "$as_me:14642: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16832,11 +16842,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16835: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16845: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16839: \$? = $ac_status" >&5
+   echo "$as_me:16849: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17122,11 +17132,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17125: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17135: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17129: \$? = $ac_status" >&5
+   echo "$as_me:17139: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17226,11 +17236,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17229: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17239: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17233: \$? = $ac_status" >&5
+   echo "$as_me:17243: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23332,6 +23342,14 @@ echo "$as_me: INFO: Exit: CC=${CC} CFLAGS=${CFLAGS} HOST_CFLAGS=${HOST_CFLAGS}" 
 # Prerequisites: external libraries
 #----------------------------------------------------------------------------
 
+#
+# Directory relative to hpctoolkit's prefix where we put external
+# package libraries, if we want to copy them.
+#
+hpc_ext_libs_dir=lib/hpctoolkit/ext-libs
+
+
+
 #-------------------------------------------------
 # Option: --with-externals=PATH
 #
@@ -23383,7 +23401,7 @@ fi
 
 # Check whether --with-libdwarf was given.
 if test "${with_libdwarf+set}" = set; then
-  withval=$with_libdwarf; LIBDWARF=$withval
+  withval=$with_libdwarf; LIBDWARF="$withval"
 fi
 
 
@@ -23398,8 +23416,10 @@ case "$LIBDWARF" in
 echo "$as_me: error: invalid libdwarf directory: $LIBDWARF" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+	LIBDWARF_COPY=yes
 	;;
     no )
+	LIBDWARF_COPY=no
 	;;
     * )
 	{ { echo "$as_me:$LINENO: error: libdwarf directory must be absolute path: $LIBDWARF" >&5
@@ -23415,6 +23435,8 @@ echo "${ECHO_T}$LIBDWARF" >&6; }
 
 
 
+
+
 #-------------------------------------------------
 # Option: --with-libelf=PATH
 #-------------------------------------------------
@@ -23427,7 +23449,7 @@ fi
 
 # Check whether --with-libelf was given.
 if test "${with_libelf+set}" = set; then
-  withval=$with_libelf; LIBELF=$withval
+  withval=$with_libelf; LIBELF="$withval"
 fi
 
 
@@ -23447,8 +23469,10 @@ case "$LIBELF" in
 echo "$as_me: error: invalid libelf directory: $LIBELF" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+	LIBELF_COPY=yes
 	;;
     no )
+	LIBELF_COPY=no
 	;;
     * )
 	{ { echo "$as_me:$LINENO: error: libelf directory must be absolute path: $LIBELF" >&5
@@ -23464,6 +23488,8 @@ echo "${ECHO_T}$LIBELF" >&6; }
 
 
 
+
+
 #-------------------------------------------------
 # Option: --with-libmonitor=PATH
 #-------------------------------------------------
@@ -23476,7 +23502,7 @@ fi
 
 # Check whether --with-libmonitor was given.
 if test "${with_libmonitor+set}" = set; then
-  withval=$with_libmonitor; LIBMONITOR=$withval
+  withval=$with_libmonitor; LIBMONITOR="$withval"
 fi
 
 
@@ -23485,14 +23511,26 @@ echo $ECHO_N "checking for libmonitor... $ECHO_C" >&6; }
 
 case "$LIBMONITOR" in
     /* )
-	if test -f "${LIBMONITOR}/include/monitor.h" ; then :
+	LIBMONITOR_INC="${LIBMONITOR}/include"
+	if test -f "${LIBMONITOR_INC}/monitor.h" ; then :
 	else
 	    { { echo "$as_me:$LINENO: error: invalid libmonitor directory: $LIBMONITOR" >&5
 echo "$as_me: error: invalid libmonitor directory: $LIBMONITOR" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+	LIBMONITOR_LIB="${LIBMONITOR}/lib"
+	if test -f "${LIBMONITOR_LIB}/libmonitor.so" ; then :
+	else
+	    { { echo "$as_me:$LINENO: error: invalid libmonitor directory: $LIBMONITOR" >&5
+echo "$as_me: error: invalid libmonitor directory: $LIBMONITOR" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	LIBMONITOR_COPY=yes
+	LIBMONITOR_RUN_DIR="$hpc_ext_libs_dir"
 	;;
     no )
+	LIBMONITOR_COPY=no
+	LIBMONITOR_RUN_DIR=no
 	;;
     * )
 	{ { echo "$as_me:$LINENO: error: libmonitor directory must be absolute path: $LIBMONITOR" >&5
@@ -23501,12 +23539,10 @@ echo "$as_me: error: libmonitor directory must be absolute path: $LIBMONITOR" >&
 	;;
 esac
 
-LIBMONITOR_INC="${LIBMONITOR}/include"
-LIBMONITOR_LIB="${LIBMONITOR}/lib"
-libmonitor_prefix="$LIBMONITOR"
-
 { echo "$as_me:$LINENO: result: $LIBMONITOR" >&5
 echo "${ECHO_T}$LIBMONITOR" >&6; }
+
+
 
 
 
@@ -23524,7 +23560,7 @@ fi
 
 # Check whether --with-symtabAPI was given.
 if test "${with_symtabAPI+set}" = set; then
-  withval=$with_symtabAPI; SYMTABAPI=$withval
+  withval=$with_symtabAPI; SYMTABAPI="$withval"
 fi
 
 
@@ -23539,8 +23575,12 @@ case "$SYMTABAPI" in
 echo "$as_me: error: invalid symtabAPI directory: $SYMTABAPI" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+	SYMTABAPI_COPY=yes
+	SYMTABAPI_RUN_DIR="$hpc_ext_libs_dir"
 	;;
     no )
+	SYMTABAPI_COPY=no
+	SYMTABAPI_RUN_DIR=no
 	;;
     * )
 	{ { echo "$as_me:$LINENO: error: symtabAPI directory must be absolute path: $SYMTABAPI" >&5
@@ -23558,6 +23598,9 @@ echo "${ECHO_T}$SYMTABAPI" >&6; }
 
 
 
+
+
+
 #-------------------------------------------------
 # Option: --with-xed2=PATH
 #-------------------------------------------------
@@ -23570,7 +23613,7 @@ fi
 
 # Check whether --with-xed2 was given.
 if test "${with_xed2+set}" = set; then
-  withval=$with_xed2; XED2=$withval
+  withval=$with_xed2; XED2="$withval"
 fi
 
 
@@ -23585,8 +23628,12 @@ case "$XED2" in
 echo "$as_me: error: invalid xed2 directory: $XED2" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+	XED2_COPY=yes
+	XED2_RUN_DIR="$hpc_ext_libs_dir"
 	;;
     no )
+	XED2_COPY=no
+	XED2_RUN_DIR=no
 	;;
     * )
 	{ { echo "$as_me:$LINENO: error: xed2 directory must be absolute path: $XED2" >&5
@@ -23600,6 +23647,9 @@ XED2_LIB="${XED2}/lib"
 
 { echo "$as_me:$LINENO: result: $XED2" >&5
 echo "${ECHO_T}$XED2" >&6; }
+
+
+
 
 
 
@@ -23633,8 +23683,17 @@ fi
 XERCES_IFLAGS="-I${XERCES}/include"
 XERCES_LDFLAGS="-L${XERCES}/lib -lxerces-c"
 
+if test "$XERCES" = no ; then
+  XERCES_COPY=no
+else
+  XERCES_COPY=yes
+  XERCES_LIB="${XERCES}/lib"
+fi
+
 { echo "$as_me:$LINENO: result: ${XERCES}" >&5
 echo "${ECHO_T}${XERCES}" >&6; }
+
+
 
 
 
@@ -23734,7 +23793,7 @@ HPC_MONITOR=
 
 if test "$use_externals" = yes ; then
   OPT_WITH_MONITOR=yes
-  OPT_INSTALL_MONITOR=no
+  OPT_INSTALL_MONITOR=yes
   MONITOR="$ext_old_monitor_prefix"
 elif test "${HOST_OS}" = "Linux"; then
   OPT_WITH_MONITOR=yes
@@ -24196,6 +24255,7 @@ rm -f "$src" "$obj"
 
 
 
+
 #-------------------------------------------------
 # enable-devtools: Tools of interest to developers
 #-------------------------------------------------
@@ -24335,6 +24395,9 @@ ac_config_files="$ac_config_files src/tool/csprof/scripts/hpclink"
 
 ac_config_files="$ac_config_files src/tool/csprof/scripts/csprof_syms"
 
+
+
+export_hpctoolkit="${srcdir}/config/export-hpctoolkit"
 
 ac_config_commands="$ac_config_commands "
 
@@ -25139,6 +25202,11 @@ if test -n "$CONFIG_FILES"; then
 
 _ACEOF
 
+# Create sed commands to just substitute file output variables.
+
+# Remaining file output variables are in a fragment that also has non-file
+# output varibles.
+
 
 
 ac_delim='%!_!# '
@@ -25238,12 +25306,9 @@ GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 LN_S!$LN_S$ac_delim
 ECHO!$ECHO$ac_delim
-AR!$AR$ac_delim
-RANLIB!$RANLIB$ac_delim
-DSYMUTIL!$DSYMUTIL$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -25263,6 +25328,10 @@ fi
 cat >>$CONFIG_STATUS <<_ACEOF
 cat >"\$tmp/subs-1.sed" <<\CEOF$ac_eof
 /@[a-zA-Z_][a-zA-Z_0-9]*@/!b
+/^[	 ]*@export_hpctoolkit@[	 ]*$/{
+r $export_hpctoolkit
+d
+}
 _ACEOF
 sed '
 s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
@@ -25282,6 +25351,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+AR!$AR$ac_delim
+RANLIB!$RANLIB$ac_delim
+DSYMUTIL!$DSYMUTIL$ac_delim
 NMEDIT!$NMEDIT$ac_delim
 CPP!$CPP$ac_delim
 CXX!$CXX$ac_delim
@@ -25314,18 +25386,28 @@ HOST_HPCPROF_LDFLAGS!$HOST_HPCPROF_LDFLAGS$ac_delim
 HOST_HPCPROF_FLAT_LDFLAGS!$HOST_HPCPROF_FLAT_LDFLAGS$ac_delim
 HOST_HPCPROFTT_LDFLAGS!$HOST_HPCPROFTT_LDFLAGS$ac_delim
 HOST_XPROF_LDFLAGS!$HOST_XPROF_LDFLAGS$ac_delim
+hpc_ext_libs_dir!$hpc_ext_libs_dir$ac_delim
 LIBDWARF_LIB!$LIBDWARF_LIB$ac_delim
+LIBDWARF_COPY!$LIBDWARF_COPY$ac_delim
 LIBELF_LIB!$LIBELF_LIB$ac_delim
+LIBELF_COPY!$LIBELF_COPY$ac_delim
 LIBMONITOR_INC!$LIBMONITOR_INC$ac_delim
 LIBMONITOR_LIB!$LIBMONITOR_LIB$ac_delim
-libmonitor_prefix!$libmonitor_prefix$ac_delim
+LIBMONITOR_COPY!$LIBMONITOR_COPY$ac_delim
+LIBMONITOR_RUN_DIR!$LIBMONITOR_RUN_DIR$ac_delim
 SYMTABAPI_INC!$SYMTABAPI_INC$ac_delim
 SYMTABAPI_LIB!$SYMTABAPI_LIB$ac_delim
+SYMTABAPI_COPY!$SYMTABAPI_COPY$ac_delim
+SYMTABAPI_RUN_DIR!$SYMTABAPI_RUN_DIR$ac_delim
 XED2_INC!$XED2_INC$ac_delim
 XED2_LIB!$XED2_LIB$ac_delim
+XED2_COPY!$XED2_COPY$ac_delim
+XED2_RUN_DIR!$XED2_RUN_DIR$ac_delim
 XERCES!$XERCES$ac_delim
 XERCES_IFLAGS!$XERCES_IFLAGS$ac_delim
 XERCES_LDFLAGS!$XERCES_LDFLAGS$ac_delim
+XERCES_COPY!$XERCES_COPY$ac_delim
+XERCES_LIB!$XERCES_LIB$ac_delim
 OA_IFLAGS!$OA_IFLAGS$ac_delim
 OA_LDFLAGS!$OA_LDFLAGS$ac_delim
 GNUBINUTILS_IFLAGS!$GNUBINUTILS_IFLAGS$ac_delim
@@ -25366,7 +25448,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 82; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 95; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -25841,12 +25923,12 @@ fi
 #
 # Summary of the config options.
 #
-{ echo "$as_me:$LINENO: " >&5
-echo "$as_me: " >&6;}
+{ echo "$as_me:$LINENO: -------------------" >&5
+echo "$as_me: -------------------" >&6;}
 { echo "$as_me:$LINENO: HPCToolkit summary" >&5
 echo "$as_me: HPCToolkit summary" >&6;}
-{ echo "$as_me:$LINENO: ---------------------------------------------------------------" >&5
-echo "$as_me: ---------------------------------------------------------------" >&6;}
+{ echo "$as_me:$LINENO: -------------------" >&5
+echo "$as_me: -------------------" >&6;}
 { echo "$as_me:$LINENO:   prefix: $prefix" >&5
 echo "$as_me:   prefix: $prefix" >&6;}
 { echo "$as_me:$LINENO:   host: $host" >&5
