Add the --with-externals=PATH option as an alternate way to specify the binutils, open analysis, etc, prerequisites.  This is the first step in integrating the new build system (the replacement for OSS).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1544,6 +1544,8 @@ Optional Packages:
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
   --with-tags[=TAGS]      include additional configurations [automatic]
+
+  --with-externals=PATH   path to external prereqs tree (default no)
   --with-xerces=<XercesC path>
                           use given XercesC installation
   --with-oa=<OpenAnalysis path>
@@ -4487,7 +4489,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4490 "configure"' > conftest.$ac_ext
+  echo '#line 4492 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7544,11 +7546,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7547: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7549: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7551: \$? = $ac_status" >&5
+   echo "$as_me:7553: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7834,11 +7836,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7837: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7839: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7841: \$? = $ac_status" >&5
+   echo "$as_me:7843: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7938,11 +7940,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7941: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7943: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7945: \$? = $ac_status" >&5
+   echo "$as_me:7947: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10302,7 +10304,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10305 "configure"
+#line 10307 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10402,7 +10404,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10405 "configure"
+#line 10407 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12803,11 +12805,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12806: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12808: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12810: \$? = $ac_status" >&5
+   echo "$as_me:12812: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12907,11 +12909,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12910: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12912: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12914: \$? = $ac_status" >&5
+   echo "$as_me:12916: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14490,11 +14492,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14493: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14495: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14497: \$? = $ac_status" >&5
+   echo "$as_me:14499: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14594,11 +14596,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14597: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14599: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14601: \$? = $ac_status" >&5
+   echo "$as_me:14603: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16801,11 +16803,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16804: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16806: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16808: \$? = $ac_status" >&5
+   echo "$as_me:16810: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17091,11 +17093,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17094: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17096: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17098: \$? = $ac_status" >&5
+   echo "$as_me:17100: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17195,11 +17197,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17198: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17200: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17202: \$? = $ac_status" >&5
+   echo "$as_me:17204: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23133,6 +23135,44 @@ echo "$as_me: INFO: Exit: CC=${CC} CFLAGS=${CFLAGS} HOST_CFLAGS=${HOST_CFLAGS}" 
 #----------------------------------------------------------------------------
 
 #-------------------------------------------------
+# Option: --with-externals=PATH
+#
+# If specified, then use PATH as the root of the external prereqs tree
+# and the file PATH/externs.conf for the locations of binutils, open
+# analysis, xerces, etc.  Default is not to use this.
+#-------------------------------------------------
+
+
+# Check whether --with-dummy-blank-line was given.
+if test "${with_dummy_blank_line+set}" = set; then
+  withval=$with_dummy_blank_line;
+fi
+
+
+# Check whether --with-externals was given.
+if test "${with_externals+set}" = set; then
+  withval=$with_externals;
+else
+  with_externals=no
+fi
+
+
+use_externals=no
+if test "x$with_externals" != xno ; then
+  ext_file="${with_externals}/externs.conf"
+  if test -f "$ext_file" ; then
+    { echo "$as_me:$LINENO: using externals file: $ext_file" >&5
+echo "$as_me: using externals file: $ext_file" >&6;}
+    . "$ext_file"
+    use_externals=yes
+  else
+    { { echo "$as_me:$LINENO: error: missing externals file: $ext_file" >&5
+echo "$as_me: error: missing externals file: $ext_file" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+fi
+
+#-------------------------------------------------
 # Check for Xerces-C (XML parser)
 #-------------------------------------------------
 
@@ -23153,6 +23193,10 @@ if test "${with_xerces+set}" = set; then
    fi
 fi
 
+
+if test "$use_externals" = yes ; then
+  XERCES="$ext_xerces_prefix"
+fi
 
 XERCES_IFLAGS="-I${XERCES}/include"
 XERCES_LDFLAGS="-L${XERCES}/lib -lxerces-c"
@@ -23182,6 +23226,10 @@ if test "${with_oa+set}" = set; then
 fi
 
 
+if test "$use_externals" = yes ; then
+  OA="$ext_open_analysis_prefix"
+fi
+
 OA_IFLAGS="-DOA_IRHANDLETYPE_SZ64 -I${OA}/include"
 OA_LDFLAGS="-L${OA}/lib -lOAsz64"
 
@@ -23210,6 +23258,9 @@ if test "${with_binutils+set}" = set; then
 fi
 
 
+if test "$use_externals" = yes ; then
+  GNUBINUTILS="$ext_binutils_prefix"
+fi
 
 # The binutils installer (2.16.1, 2.17) creates libbfd.la and
 # libopcodes.la but only libiberty.a.  Apparently, not having
@@ -23247,7 +23298,6 @@ MONITOR=
 MONITOR_LIBS=
 HPC_MONITOR=
 
-
 # Use monitor by default
 if test "${HOST_OS}" = "Linux"; then
   OPT_WITH_MONITOR=yes
@@ -23268,6 +23318,12 @@ if test "${with_monitor+set}" = set; then
 fi
 
 
+if test "$use_externals" = yes ; then
+  OPT_WITH_MONITOR=yes
+  OPT_INSTALL_MONITOR=no
+  MONITOR="$ext_old_monitor_prefix"
+fi
+
 for lib in ${LIB_SEARCH_PATH} ; do
   if test -r "${MONITOR}/${lib}/libmonitor.so"; then
     MONITOR_LIBS="${MONITOR_LIBS} ${MONITOR}/${lib}/libmonitor.so"
@@ -23282,7 +23338,6 @@ if test "${OPT_INSTALL_MONITOR}" = "yes" ; then
 else
   HPC_MONITOR="${MONITOR}"
 fi
-
 
 if test "${OPT_WITH_MONITOR}" = "yes" ; then
 
