Fix objcopy in the install script in libunwind not to assume that it always builds both static and shared libraries.  This was failing on systems that don't normally build shared libraries.
Thanks to: Gabriel Marin at ORNL for reporting the problem.

diff --git a/externals/libunwind/install b/externals/libunwind/install
--- a/externals/libunwind/install
+++ b/externals/libunwind/install
@@ -41,11 +41,13 @@ do
 done
 
 cd "${prefix}/lib" || die "unable to cd: ${prefix}/lib"
-for file in libunwind.a libunwind.so.7.0.0
+for file in libunwind.a libunwind.so*
 do
-    echo objcopy "$@" "$file"
-    objcopy "$@" "$file"
-    test $? -eq 0 || die "objcopy failed: $file"
+    if test -f "$file" && test ! -L "$file" ; then
+	echo objcopy "$@" "$file"
+	objcopy "$@" "$file"
+	test $? -eq 0 || die "objcopy failed: $file"
+    fi
 done
 
 post_install
