Cleanup (coordinated with changes to HPCToolkitOSS configure.ac).

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -837,6 +837,8 @@ host_cpu
 host_vendor
 host_os
 HPCTOOLKIT_PLATFORM
+OPT_ENABLE_DEVELOP_TRUE
+OPT_ENABLE_DEVELOP_FALSE
 CC
 CFLAGS
 LDFLAGS
@@ -872,8 +874,6 @@ F77
 FFLAGS
 ac_ct_F77
 LIBTOOL
-OPT_ENABLE_DEVELOP_TRUE
-OPT_ENABLE_DEVELOP_FALSE
 HOST_CFLAGS
 HOST_CXXFLAGS
 HOST_AR
@@ -1517,6 +1517,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-develop        Build development version (enable debugging)
   --enable-shared[=PKGS]  build shared libraries [default=yes]
   --enable-static[=PKGS]  build static libraries [default=yes]
   --enable-fast-install[=PKGS]
@@ -1524,7 +1525,6 @@ Optional Features:
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --disable-libtool-lock  avoid locking (might break parallel builds)
-  --enable-develop        Build development version (enable debugging)
   --enable-csprof-sync    Build csprof (synchronous)
   --enable-csprof-async   Build csprof (synchronous)
   --enable-devtools       Build development tools (enable debugging)
@@ -2585,6 +2585,45 @@ echo "$as_me: INFO: On entry: CC=${CC} CFLAGS=${CFLAGS}" >&6;}
 hpctoolkit_top=`cd ${srcdir} && pwd`
 hpctoolkit_build=`pwd`
 HPCTOOLKIT_PLATFORM=`cd ${hpctoolkit_top}/config && ./hpcplatform`
+
+
+
+#----------------------------------------------------------------------------
+# Special Options that should be tested first
+#----------------------------------------------------------------------------
+
+#-------------------------------------------------
+# enable-develop
+#-------------------------------------------------
+
+{ echo "$as_me:$LINENO: checking whether DEVELOP mode is enabled" >&5
+echo $ECHO_N "checking whether DEVELOP mode is enabled... $ECHO_C" >&6; }
+
+OPT_ENABLE_DEVELOP=no
+
+# Check whether --enable-develop was given.
+if test "${enable_develop+set}" = set; then
+  enableval=$enable_develop; case "${enableval}" in
+     yes) OPT_ENABLE_DEVELOP="yes" ;;
+     no)  OPT_ENABLE_DEVELOP="no" ;;
+     *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-develop" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-develop" >&2;}
+   { (exit 1); exit 1; }; } ;;
+   esac
+else
+  OPT_ENABLE_DEVELOP=no
+fi
+
+
+{ echo "$as_me:$LINENO: result: ${OPT_ENABLE_DEVELOP}" >&5
+echo "${ECHO_T}${OPT_ENABLE_DEVELOP}" >&6; }
+ if test "${OPT_ENABLE_DEVELOP}" = "yes"; then
+  OPT_ENABLE_DEVELOP_TRUE=
+  OPT_ENABLE_DEVELOP_FALSE='#'
+else
+  OPT_ENABLE_DEVELOP_TRUE='#'
+  OPT_ENABLE_DEVELOP_FALSE=
+fi
 
 
 
@@ -4419,7 +4458,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4422 "configure"' > conftest.$ac_ext
+  echo '#line 4461 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7158,11 +7197,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7161: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7200: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7165: \$? = $ac_status" >&5
+   echo "$as_me:7204: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7448,11 +7487,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7451: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7490: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7455: \$? = $ac_status" >&5
+   echo "$as_me:7494: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7552,11 +7591,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7555: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7594: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7559: \$? = $ac_status" >&5
+   echo "$as_me:7598: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9897,7 +9936,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9900 "configure"
+#line 9939 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9997,7 +10036,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10000 "configure"
+#line 10039 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12412,11 +12451,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12415: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12454: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12419: \$? = $ac_status" >&5
+   echo "$as_me:12458: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12516,11 +12555,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12519: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12558: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12523: \$? = $ac_status" >&5
+   echo "$as_me:12562: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14077,11 +14116,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14080: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14119: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14084: \$? = $ac_status" >&5
+   echo "$as_me:14123: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14181,11 +14220,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14184: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14223: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14188: \$? = $ac_status" >&5
+   echo "$as_me:14227: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16363,11 +16402,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16366: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16405: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16370: \$? = $ac_status" >&5
+   echo "$as_me:16409: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16653,11 +16692,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16656: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16695: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16660: \$? = $ac_status" >&5
+   echo "$as_me:16699: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16757,11 +16796,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16760: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16799: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16764: \$? = $ac_status" >&5
+   echo "$as_me:16803: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22347,44 +22386,6 @@ echo "${ECHO_T}${HAVE_OS_MULTILIB} (searching: ${LIB_SEARCH_PATH})" >&6; }
 # -none thus far-
 
 
-#----------------------------------------------------------------------------
-# Special Options that should be tested first
-#----------------------------------------------------------------------------
-
-#-------------------------------------------------
-# enable-develop
-#-------------------------------------------------
-
-{ echo "$as_me:$LINENO: checking whether DEVELOP mode is enabled" >&5
-echo $ECHO_N "checking whether DEVELOP mode is enabled... $ECHO_C" >&6; }
-
-OPT_ENABLE_DEVELOP=no
-
-# Check whether --enable-develop was given.
-if test "${enable_develop+set}" = set; then
-  enableval=$enable_develop; case "${enableval}" in
-     yes) OPT_ENABLE_DEVELOP="yes" ;;
-     no)  OPT_ENABLE_DEVELOP="no" ;;
-     *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-develop" >&5
-echo "$as_me: error: bad value ${enableval} for --enable-develop" >&2;}
-   { (exit 1); exit 1; }; } ;;
-   esac
-else
-  OPT_ENABLE_DEVELOP=no
-fi
-
-
-{ echo "$as_me:$LINENO: result: ${OPT_ENABLE_DEVELOP}" >&5
-echo "${ECHO_T}${OPT_ENABLE_DEVELOP}" >&6; }
- if test "${OPT_ENABLE_DEVELOP}" = "yes"; then
-  OPT_ENABLE_DEVELOP_TRUE=
-  OPT_ENABLE_DEVELOP_FALSE='#'
-else
-  OPT_ENABLE_DEVELOP_TRUE='#'
-  OPT_ENABLE_DEVELOP_FALSE=
-fi
-
-
 
 #----------------------------------------------------------------------------
 # Host-dependent configuration
@@ -22406,7 +22407,7 @@ MYcxxcmp()
    }
 
 #-------------------------------------------------
-# Host-specific defines for HPCToolkit
+# Host-specific defines
 #-------------------------------------------------
 
 # NOTE: To see what macros gcc-like compilers define:
@@ -22496,7 +22497,7 @@ esac
 
 
 #-------------------------------------------------
-# Host-specific compiler settings for HPCToolkit
+# Host-specific compiler settings
 #-------------------------------------------------
 
 # FIXME: Now that we use libtool to build all HPCToolkit libraries, we
@@ -23424,6 +23425,13 @@ LIBOBJS=$ac_libobjs
 LTLIBOBJS=$ac_ltlibobjs
 
 
+if test -z "${OPT_ENABLE_DEVELOP_TRUE}" && test -z "${OPT_ENABLE_DEVELOP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"OPT_ENABLE_DEVELOP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"OPT_ENABLE_DEVELOP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -23456,13 +23464,6 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${OPT_ENABLE_DEVELOP_TRUE}" && test -z "${OPT_ENABLE_DEVELOP_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"OPT_ENABLE_DEVELOP\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"OPT_ENABLE_DEVELOP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24126,6 +24127,8 @@ host_cpu!$host_cpu$ac_delim
 host_vendor!$host_vendor$ac_delim
 host_os!$host_os$ac_delim
 HPCTOOLKIT_PLATFORM!$HPCTOOLKIT_PLATFORM$ac_delim
+OPT_ENABLE_DEVELOP_TRUE!$OPT_ENABLE_DEVELOP_TRUE$ac_delim
+OPT_ENABLE_DEVELOP_FALSE!$OPT_ENABLE_DEVELOP_FALSE$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -24153,8 +24156,6 @@ CPP!$CPP$ac_delim
 CXX!$CXX$ac_delim
 CXXFLAGS!$CXXFLAGS$ac_delim
 ac_ct_CXX!$ac_ct_CXX$ac_delim
-CXXDEPMODE!$CXXDEPMODE$ac_delim
-am__fastdepCXX_TRUE!$am__fastdepCXX_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -24196,14 +24197,14 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CXXDEPMODE!$CXXDEPMODE$ac_delim
+am__fastdepCXX_TRUE!$am__fastdepCXX_TRUE$ac_delim
 am__fastdepCXX_FALSE!$am__fastdepCXX_FALSE$ac_delim
 CXXCPP!$CXXCPP$ac_delim
 F77!$F77$ac_delim
 FFLAGS!$FFLAGS$ac_delim
 ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
-OPT_ENABLE_DEVELOP_TRUE!$OPT_ENABLE_DEVELOP_TRUE$ac_delim
-OPT_ENABLE_DEVELOP_FALSE!$OPT_ENABLE_DEVELOP_FALSE$ac_delim
 HOST_CFLAGS!$HOST_CFLAGS$ac_delim
 HOST_CXXFLAGS!$HOST_CXXFLAGS$ac_delim
 HOST_AR!$HOST_AR$ac_delim
