Fix bug introduced in r842:   - at this time, libhpcrun.so must link with libpapi.so (unless the papi factorization is completed.  I forgot that I had only factored papi from hpcrun and not from libhpcrun.so)   - detect correct papi for multilib

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -901,6 +901,7 @@ OPT_HAVE_PAPI_TRUE
 OPT_HAVE_PAPI_FALSE
 OPT_PAPI
 OPT_PAPI_IFLAGS
+OPT_PAPI_LDFLAGS
 OPT_HAVE_LIBUNWIND_TRUE
 OPT_HAVE_LIBUNWIND_FALSE
 OPT_LIBUNWIND_IFLAGS
@@ -4416,7 +4417,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4419 "configure"' > conftest.$ac_ext
+  echo '#line 4420 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7155,11 +7156,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7158: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7159: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7162: \$? = $ac_status" >&5
+   echo "$as_me:7163: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7445,11 +7446,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7448: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7449: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7452: \$? = $ac_status" >&5
+   echo "$as_me:7453: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7549,11 +7550,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7552: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7553: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7556: \$? = $ac_status" >&5
+   echo "$as_me:7557: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9894,7 +9895,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9897 "configure"
+#line 9898 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9994,7 +9995,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9997 "configure"
+#line 9998 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12409,11 +12410,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12412: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12413: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12416: \$? = $ac_status" >&5
+   echo "$as_me:12417: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12513,11 +12514,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12516: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12517: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12520: \$? = $ac_status" >&5
+   echo "$as_me:12521: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14074,11 +14075,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14077: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14078: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14081: \$? = $ac_status" >&5
+   echo "$as_me:14082: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14178,11 +14179,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14181: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14182: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14185: \$? = $ac_status" >&5
+   echo "$as_me:14186: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16360,11 +16361,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16363: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16364: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16367: \$? = $ac_status" >&5
+   echo "$as_me:16368: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16650,11 +16651,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16653: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16654: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16657: \$? = $ac_status" >&5
+   echo "$as_me:16658: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16754,11 +16755,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16757: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16758: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16761: \$? = $ac_status" >&5
+   echo "$as_me:16762: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22864,7 +22865,9 @@ HPC_check_cxx_papi_link()
      CXXFLAGS_ORIG=${CXXFLAGS}
      CXXFLAGS="${CXXFLAGS} ${myincflg}"
      LDFLAGS_ORIG=${LDFLAGS}
-     LDFLAGS="${LDFLAGS} -L$mylibpath -lpapi -lperfctr"
+     LIBS_ORIG=${LIBS}
+     LIBS="${LIBS} ${mylibpath}/libpapi.a"
+     #LIBS="${LIBS} -L${mylibpath} -lpapi"
 
      { echo "$as_me:$LINENO: checking whether ${CXX-CC} can link with PAPI using path ${mylibpath}" >&5
 echo $ECHO_N "checking whether ${CXX-CC} can link with PAPI using path ${mylibpath}... $ECHO_C" >&6; }
@@ -22883,7 +22886,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-PAPI_num_counters()
+PAPI_is_initialized()
   ;
   return 0;
 }
@@ -22923,6 +22926,7 @@ echo "${ECHO_T}$ac_cv_check_cxx_papi_link" >&6; }
 
      CXXFLAGS="${CXXFLAGS_ORIG}"
      LDFLAGS="${LDFLAGS_ORIG}"
+     LIBS="${LIBS_ORIG}"
 
      if test "$ac_cv_check_cxx_papi_link" = "yes" ; then
        return 0
@@ -22977,35 +22981,36 @@ if test "$OPT_HAVE_PAPI" = "yes" ; then
     OPT_PAPI_IFLAGS="-I${OPT_PAPI}"
   fi
 
-  # Disable for now: 1) we dlopen papi; and 2) HPC_check_cxx_papi_link problem
-  #for lib in ${LIB_SEARCH_PATH} ; do
-  #  if test -r "${OPT_PAPI}/${lib}/libpapi.so"; then
-  #    if HPC_check_cxx_papi_link ${OPT_PAPI_IFLAGS} ${OPT_PAPI}/${lib} ; then
-  #      OPT_PAPI_LIB="${OPT_PAPI}/${lib}/libpapi.so"
-  #      OPT_PAPI_LDFLAGS="${OPT_PAPI}/${lib} -lpapi"
-  #      break;
-  #    fi
-  #  fi
-  #done
-
   for lib in ${LIB_SEARCH_PATH} ; do
     if test -r "${OPT_PAPI}/${lib}/libpapi.so"; then
-      OPT_PAPI_LIB="${OPT_PAPI_LIB} ${OPT_PAPI}/${lib}/libpapi.so"
+      if HPC_check_cxx_papi_link ${OPT_PAPI_IFLAGS} ${OPT_PAPI}/${lib} ; then
+        OPT_PAPI_LIB="${OPT_PAPI}/${lib}/libpapi.so"
+        OPT_PAPI_LDFLAGS="-L${OPT_PAPI}/${lib} -lpapi"
+        break;
+      fi
     fi
   done
-  OPT_PAPI_LIB=`echo ${OPT_PAPI_LIB}`
 
-fi
+  #for lib in ${LIB_SEARCH_PATH} ; do
+  #  if test -r "${OPT_PAPI}/${lib}/libpapi.so"; then
+  #    OPT_PAPI_LIB="${OPT_PAPI_LIB} ${OPT_PAPI}/${lib}/libpapi.so"
+  #  fi
+  #done
+  #OPT_PAPI_LIB=`echo ${OPT_PAPI_LIB}`
 
-if test -z "${OPT_PAPI_LIB}" ; then
-  OPT_HAVE_PAPI="no"
 fi
 
 # Check for PAPI > 3.0 [skip for now]
 
 if test "${OPT_HAVE_PAPI}" = "yes"; then
-  { echo "$as_me:$LINENO: result: yes (${OPT_PAPI_LIB})" >&5
+  if test -n "${OPT_PAPI_LIB}" ; then
+    { echo "$as_me:$LINENO: result: yes (${OPT_PAPI_LIB})" >&5
 echo "${ECHO_T}yes (${OPT_PAPI_LIB})" >&6; }
+  else
+    { { echo "$as_me:$LINENO: error: cannot find usable PAPI in '${LIB_SEARCH_PATH}'" >&5
+echo "$as_me: error: cannot find usable PAPI in '${LIB_SEARCH_PATH}'" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -23021,7 +23026,7 @@ fi
 
 
 
-#AC_SUBST(OPT_PAPI_LDFLAGS)
+
 
 
 #-------------------------------------------------
@@ -24220,6 +24225,7 @@ OPT_HAVE_PAPI_TRUE!$OPT_HAVE_PAPI_TRUE$ac_delim
 OPT_HAVE_PAPI_FALSE!$OPT_HAVE_PAPI_FALSE$ac_delim
 OPT_PAPI!$OPT_PAPI$ac_delim
 OPT_PAPI_IFLAGS!$OPT_PAPI_IFLAGS$ac_delim
+OPT_PAPI_LDFLAGS!$OPT_PAPI_LDFLAGS$ac_delim
 OPT_HAVE_LIBUNWIND_TRUE!$OPT_HAVE_LIBUNWIND_TRUE$ac_delim
 OPT_HAVE_LIBUNWIND_FALSE!$OPT_HAVE_LIBUNWIND_FALSE$ac_delim
 OPT_LIBUNWIND_IFLAGS!$OPT_LIBUNWIND_IFLAGS$ac_delim
@@ -24240,7 +24246,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 54; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
