Turn on symtabAPI exception block handling in hpcfnbounds. Reindent one section to be more consistent with existing style.
Note: hpctoolkit now requires rev 1714 or later from externals.

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -23269,7 +23269,7 @@ hpc_ext_libs_dir=lib/hpctoolkit/ext-libs
 #-------------------------------------------------
 
 # External's minimum svn rev number, or else a fatal error.
-EXTERNALS_MIN_REV=1600
+EXTERNALS_MIN_REV=1714
 
 
 # Check whether --with-dummy-blank-line was given.
@@ -23288,29 +23288,29 @@ fi
 
 if test "x$with_externals" != xno
 then
-    ext_file="${with_externals}/externs.conf"
-    if test ! -f "$ext_file" ; then
-	{ { echo "$as_me:$LINENO: error: missing externals file: $ext_file" >&5
+  ext_file="${with_externals}/externs.conf"
+  if test ! -f "$ext_file" ; then
+    { { echo "$as_me:$LINENO: error: missing externals file: $ext_file" >&5
 echo "$as_me: error: missing externals file: $ext_file" >&2;}
    { (exit 1); exit 1; }; }
-    fi
-    { echo "$as_me:$LINENO: using externals tree: $with_externals" >&5
+  fi
+  { echo "$as_me:$LINENO: using externals tree: $with_externals" >&5
 echo "$as_me: using externals tree: $with_externals" >&6;}
-    externals_root=`( cd "$with_externals" && pwd )`
-    . "$ext_file"
-    if test "$ext_version" -ge "$EXTERNALS_MIN_REV" ; then :
-    else
-	{ { echo "$as_me:$LINENO: error: externals tree too old, update to rev $EXTERNALS_MIN_REV" >&5
-echo "$as_me: error: externals tree too old, update to rev $EXTERNALS_MIN_REV" >&2;}
+  externals_root=`( cd "$with_externals" && pwd )`
+  . "$ext_file"
+  if test "$ext_version" -ge "$EXTERNALS_MIN_REV" ; then :
+  else
+    { { echo "$as_me:$LINENO: error: externals tree too old, update to revision $EXTERNALS_MIN_REV or later" >&5
+echo "$as_me: error: externals tree too old, update to revision $EXTERNALS_MIN_REV or later" >&2;}
    { (exit 1); exit 1; }; }
-    fi
-    use_externals=yes
-    externals_mesg="$ext_version"
+  fi
+  use_externals=yes
+  externals_mesg="$ext_version"
 else
-    { echo "$as_me:$LINENO: WARNING: not using --with-externals" >&5
+  { echo "$as_me:$LINENO: WARNING: not using --with-externals" >&5
 echo "$as_me: WARNING: not using --with-externals" >&2;}
-    use_externals=no
-    externals_mesg=no
+  use_externals=no
+  externals_mesg=no
 fi
 
 
