hpcrun: Remove references to dependency install prefixes
Meson doesn't have install prefixes for dependencies. The only place
the `hpcrun` launch script uses them is to fill in `LD_LIBRARY_PATH`,
but there should already be R*PATHs in libhpcrun.so for that sort of
thing. So remove them.

The only unique case is libmonitor.so, which needs to be listed in
`LD_PRELOAD` as well. This one is worked around by using `ldd` on the
main libhpcrun.so, which links against libmonitor.so. This weirdness
can be removed once [#793] is implemented.

[#793]: https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/793

diff --git a/src/tool/hpcrun/hpcrun.in b/src/tool/hpcrun/hpcrun.in
--- a/src/tool/hpcrun/hpcrun.in
+++ b/src/tool/hpcrun/hpcrun.in
@@ -16,10 +16,6 @@
 # Relative paths are relative to HPCTOOLKIT.
 hpcfnbounds_dir='libexec/hpctoolkit'
 hpcrun_dir='lib/hpctoolkit'
-libmonitor_dir='@LIBMONITOR_LIB@'
-papi_libdir='@OPT_PAPI_LIBPATH@'
-perfmon_libdir='@PERFMON_LIB@'
-gtpin_lib_path='@OPT_GTPIN_LIBDIR@'
 host_arm='@HOST_CPU_AARCH64@'
 prog_name=hpcrun
 
@@ -331,13 +327,12 @@ non_empty()
     esac
 }
 
-# Process options and export environ variables.  LD_LIBRARY_PATH and
+# Process options and export environ variables.
 # LD_PRELOAD should be delayed until we launch the program, but the
 # others can be set now.
 
 audit_list=
 preload_list=
-gtpin_libdir=
 namespace_default=multiple
 namespace_multiple=
 namespace_single=
@@ -477,7 +472,6 @@ do
                     if test "$opt_have_gtpin" != yes ; then
                         die "HPCToolkit was not compiled with GTPin support enabled"
                     fi
-                    gtpin_libdir="${gtpin_lib_path}"
                     export ZET_ENABLE_PROGRAM_INSTRUMENTATION=1
                     export ZE_ENABLE_TRACING_LAYER=1
                     preload_list="${preload_list:+${preload_list}:}${hpcrun_dir}/libhpcrun_level0.so"
@@ -813,19 +807,17 @@ fi
 ulimit -S -c unlimited >/dev/null 2>&1
 
 #------------------------------------------------------------
-# assemble hpc_ld_library_path without any empty entries
-#------------------------------------------------------------
-
-hpc_ld_library_path="${hpcrun_dir}"
-hpc_ld_library_path="${hpc_ld_library_path}${papi_libdir:+:${papi_libdir}}"
-hpc_ld_library_path="${hpc_ld_library_path}${perfmon_libdir:+:${perfmon_libdir}}"
-hpc_ld_library_path="${hpc_ld_library_path}${gtpin_libdir:+:${gtpin_libdir}}"
-
-#------------------------------------------------------------
 # assemble preload list
 #------------------------------------------------------------
 
-preload_list="${libmonitor_dir}/libmonitor.so${preload_list:+:${preload_list}}"
+# Determine the path for libmonitor using ldd, and inject it with LD_PRELOAD
+if ! libmonitor="$(ldd "${hpcrun_dir}/libhpcrun.so" | grep -o '/.*/libmonitor.so[^[:space:]]*')"; then
+  echo 'hpcrun: failed to find libmonitor.so for preloading'
+  exit 1
+fi
+preload_list="${libmonitor}${preload_list:+:${preload_list}}"
+
+# Inject the main libhpcrun.so with LD_PRELOAD
 preload_list="${hpcrun_dir}/libhpcrun.so${preload_list:+:${preload_list}}"
 
 # Set up the auditor or fake auditor, depending on what's configured.
@@ -850,12 +842,6 @@ export HPCRUN_FNBOUNDS_CMD
 
 export HPCRUN_AUDIT_MAIN_LIB="${hpcrun_dir}/libhpcrun.so"
 
-if test -n "${hpc_ld_library_path}"; then
-  LD_LIBRARY_PATH="${hpc_ld_library_path}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
-fi
-
-if test -z "${LD_LIBRARY_PATH}"; then unset LD_LIBRARY_PATH; fi
-
 if test -n "${preload_list}"; then
   LD_PRELOAD="${preload_list}${LD_PRELOAD:+:${LD_PRELOAD}}"
 fi
@@ -866,5 +852,5 @@ if test -n "${audit_list}"; then
 fi
 if test -z "${LD_AUDIT}"; then unset LD_AUDIT; fi
 
-export LD_LIBRARY_PATH LD_PRELOAD LD_AUDIT
+export LD_PRELOAD LD_AUDIT
 exec "$@"
