Fix hpclink to handle the cross-compile link problem of needing hpcfnbounds from the front-end tree and all the libraries, PAPI and CC from the back-end tree.
The solution here is to run hpclink from the back-end install with an
option (--front-end) to specify the install directory (prefix) of the
front-end tree.  For example:

  hpclink --front-end /front/end/prefix cross-gcc file ...

The other way of running hpclink from the front-end tree with an
option for the back-end tree is possible but more complicated.  The
problem is that the back-end tree doesn't have a convenient way of
specifying CC or locating PAPI (not copied to ext-libs) without
writing these values to a config file.

diff --git a/trunk/src/tool/hpcrun/scripts/hpclink.in b/trunk/src/tool/hpcrun/scripts/hpclink.in
--- a/trunk/src/tool/hpcrun/scripts/hpclink.in
+++ b/trunk/src/tool/hpcrun/scripts/hpclink.in
@@ -83,7 +83,7 @@ extra_wrap_names=
 extra_hpc_files=
 
 # Compiler and flags for array of fnbounds addresses.
-CC='gcc @wordsize_cflag@'
+CC='@CC@ @CFLAGS@'
 
 hello="_hpc_hello_$$"
 nm_addrs="_hpc_nm_addrs_$$"
@@ -152,6 +152,11 @@ Options: Linking
                        of -Wl).  Used to work around problems with the 
                        Berkeley UPC compiler script (rarely needed).
 
+  -fe <dir>, --front-end <dir>
+                       In a cross-compile link, use the current install tree
+                       for the back-end libraries and use <dir> for the install
+                       directory (prefix) of the front-end tools (hpcfnbounds).
+
   --io                 Include the IO bytes read and written library.
 
   --ga                 Include GA (Global Arrays) wrappers.
@@ -181,10 +186,6 @@ case "$ext_libs_dir" in
     /* ) ;;
     * )  ext_libs_dir="${HPCTOOLKIT}/${ext_libs_dir}" ;;
 esac
-case "$hpcfnbounds_dir" in
-    /* ) ;;
-    * )  hpcfnbounds_dir="${HPCTOOLKIT}/${hpcfnbounds_dir}" ;;
-esac
 case "$libhpcrun_dir" in
     /* ) ;;
     * )  libhpcrun_dir="${HPCTOOLKIT}/${libhpcrun_dir}" ;;
@@ -202,9 +203,6 @@ case "$libunwind_dir" in
     * )  libunwind_dir="${HPCTOOLKIT}/${libunwind_dir}" ;;
 esac
 
-hpcfnbounds="${hpcfnbounds_dir}/hpcfnbounds"
-test -x "$hpcfnbounds" || die "missing hpcfnbounds: $hpcfnbounds"
-
 LD_LIBRARY_PATH="${ext_libs_dir}:${LD_LIBRARY_PATH}"
 export LD_LIBRARY_PATH
 
@@ -213,6 +211,7 @@ export LD_LIBRARY_PATH
 #------------------------------------------------------------
 
 double_wrap=no
+front_end_dir=no
 my_plugin_list=
 verbose=no
 verb=:
@@ -226,6 +225,11 @@ do
 	-dw | --double-wrap )
 	    double_wrap=yes
 	    shift
+	    ;;
+	-fe | -front-end | --front-end )
+	    test "x$2" != x || die "missing argument for --front-end"
+	    front_end_dir="$2"
+	    shift ; shift
 	    ;;
 	-io | --io )
 	    io_wrap="${libhpcrun_dir}/libhpcrun_io_wrap.a"
@@ -288,6 +292,23 @@ do
 	    ;;
     esac
 done
+
+#
+# In a cross-compile link, we use fnbounds from the front-end tree and
+# hpcrun libs, externals libs, PAPI and CC from the back-end tree.
+# Note: since fnbounds is a program with a launch script, we need to
+# reset HPCTOOLKIT to the front-end root before running fnbounds.
+#
+if test "$front_end_dir" != no ; then
+    HPCTOOLKIT=`cd "$front_end_dir" && pwd`
+    if test ! -d "$HPCTOOLKIT" ; then
+        die "bad front-end directory: $front_end_dir"
+    fi
+fi
+
+hpcfnbounds_dir="${HPCTOOLKIT}/${hpcfnbounds_dir}"
+hpcfnbounds="${hpcfnbounds_dir}/hpcfnbounds"
+test -x "$hpcfnbounds" || die "missing hpcfnbounds: $hpcfnbounds"
 
 #
 # Add plugin files: hpclink --plugin name
