Add probability-based sampling.  All processes take samples, but if HPCRUN_SAMPLE_PROB is set in the environment, then only a fraction of the processes (based on a pseudo-random seed) open their .log and .hpcrun files and write out their results.
HPCRUN_SAMPLE_PROB may be written as a floating point number or as a
fraction.  So, '0.10' and '1/10' are equivalent.

The decision of which processes are active is process-wide, not
per-thread (for now).

diff --git a/trunk/src/tool/hpcrun/scripts/hpcrun.in b/trunk/src/tool/hpcrun/scripts/hpcrun.in
--- a/trunk/src/tool/hpcrun/scripts/hpcrun.in
+++ b/trunk/src/tool/hpcrun/scripts/hpcrun.in
@@ -251,6 +251,12 @@ do
 	    export HPCRUN_QUIET=1
 	    ;;
 
+	-sp | --sample-prob )
+	    arg_ok "$1" || die "missing argument for $arg"
+	    export HPCRUN_SAMPLE_PROB="$1"
+	    shift
+	    ;;
+
 	-t | --trace )
 	    export HPCRUN_TRACE=1
 	    ;;
