Bring bgq branch up to rev 3826 of trunk
Add ibm-xlomp plugin for handling "idleness" & "working" metrics
for IBM's OpenMP realized with the mpixl compiler family on Argonne's BG/Q system.

diff --git a/branches/hpctoolkit-bgq/src/tool/hpcrun/scripts/hpclink.in b/branches/hpctoolkit-bgq/src/tool/hpcrun/scripts/hpclink.in
--- a/branches/hpctoolkit-bgq/src/tool/hpcrun/scripts/hpclink.in
+++ b/branches/hpctoolkit-bgq/src/tool/hpcrun/scripts/hpclink.in
@@ -75,7 +75,6 @@ papi_extra_libs='@papi_extra_libs@'
 
 upc_libs='@OPT_UPC_LDFLAGS@'
 
-# FIXME: The wrap list should come from monitor.
 hpctk_wrap_names='@LIBMONITOR_WRAP_NAMES@  @hpclink_extra_wrap_names@'
 
 extra_wrap_names=
@@ -154,6 +153,8 @@ Options: Linking
 
   --io                 Include the IO bytes read and written library.
 
+  --ga                 Include GA (Global Arrays) wrappers.
+
   --memleak            Include HPCToolkit's memory leak detection libraries.
 
   --plugin name        Add the libraries and wrapped symbols specified by
@@ -225,8 +226,21 @@ do
 	    io_wrap="${libhpcrun_dir}/libhpcrun_io_wrap.a"
 	    test -f "$io_wrap" || die "unable to find: $io_wrap"
 	    extra_hpc_files="$extra_hpc_files $io_wrap"
-	    extra_wrap_names="$extra_wrap_names fread fwrite"
+	    extra_wrap_names="$extra_wrap_names read write fread fwrite"
 	    undef_names="$undef_names fwrite"
+	    shift
+	    ;;
+	-ga | --ga )
+	    ga_wrap="${libhpcrun_dir}/libhpcrun_ga_wrap.a"
+	    test -f "$ga_wrap" || die "unable to find: $ga_wrap"
+	    extra_hpc_files="$extra_hpc_files $ga_wrap"
+	    extra_wrap_names="$extra_wrap_names \
+                pnga_create \
+                pnga_brdcst pnga_gop pnga_sync pnga_zero \
+                pnga_get pnga_put pnga_acc \
+                pnga_nbget pnga_nbput pnga_nbacc"
+                # pnga_nbwait
+	    undef_names="$undef_names pnga_create"
 	    shift
 	    ;;
 	-memleak | --memleak )
@@ -289,6 +303,7 @@ do
     test $? -eq 0 || die "bad plugin config file: $conf_file"
     hpclink_files=
     hpclink_wrap_names=
+    hpclink_undefined_names=
     . "$conf_file"
     for file in $hpclink_files ; do
 	case "$file" in
@@ -300,7 +315,9 @@ do
 	extra_plugin_files="$extra_plugin_files $abs_file"
     done
     $verb "plugin wrap names: $hpclink_wrap_names"
+    $verb "plugin undefined names: $hpclink_undefined_names"
     extra_wrap_names="$extra_wrap_names $hpclink_wrap_names"
+    undef_names="$undef_names $hpclink_undefined_names"
 done
 
 #
