Abstract the PGM and PROFILE (Xerces) parsing code to make a prof-juicy-x library.  This cleans up the code and anticipates using the PGM parser in xcsprof. (Though, xcsprof itself should be merged with hpcview and hpcview renamed...!)

diff --git a/branches/4.2.1-optimized-code-redesign/src/lib/prof-juicy-x/Makefile.in b/branches/4.2.1-optimized-code-redesign/src/lib/prof-juicy-x/Makefile.in
--- a/branches/4.2.1-optimized-code-redesign/src/lib/prof-juicy-x/Makefile.in
+++ b/branches/4.2.1-optimized-code-redesign/src/lib/prof-juicy-x/Makefile.in
@@ -15,7 +15,7 @@
 @SET_MAKE@
 
 # -*-Mode: makefile;-*-
-# $Id: Makefile.am 590 2006-08-02 17:32:49Z eraxxon $
+# $Id: Makefile.am 597 2006-08-10 18:11:53Z eraxxon $
 
 #############################################################################
 #
@@ -99,7 +99,7 @@ host_triplet = @host@
 DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in \
 	$(top_srcdir)/src/Makeinclude.config \
 	$(top_srcdir)/src/Makeinclude.rules
-subdir = src/lib/isa
+subdir = src/lib/prof-juicy-x
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/config/hpc-cxxutils.m4 \
 	$(top_srcdir)/configure.ac
@@ -109,12 +109,13 @@ mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
 CONFIG_CLEAN_FILES =
 LTLIBRARIES = $(noinst_LTLIBRARIES)
 am__DEPENDENCIES_1 =
-libHPCisa_la_DEPENDENCIES = $(am__DEPENDENCIES_1)
-am__objects_1 = libHPCisa_la-AlphaISA.lo libHPCisa_la-IA64ISA.lo \
-	libHPCisa_la-ISA.lo libHPCisa_la-MipsISA.lo \
-	libHPCisa_la-SparcISA.lo libHPCisa_la-x86ISA.lo
-am_libHPCisa_la_OBJECTS = $(am__objects_1)
-libHPCisa_la_OBJECTS = $(am_libHPCisa_la_OBJECTS)
+libHPCprof_juicy_x_la_DEPENDENCIES = $(am__DEPENDENCIES_1)
+am__objects_1 = libHPCprof_juicy_x_la-XercesSAX2.lo \
+	libHPCprof_juicy_x_la-XercesErrorHandler.lo \
+	libHPCprof_juicy_x_la-PGMDocHandler.lo \
+	libHPCprof_juicy_x_la-PROFILEDocHandler.lo
+am_libHPCprof_juicy_x_la_OBJECTS = $(am__objects_1)
+libHPCprof_juicy_x_la_OBJECTS = $(am_libHPCprof_juicy_x_la_OBJECTS)
 DEFAULT_INCLUDES = -I. -I$(srcdir)
 depcomp = $(SHELL) $(top_srcdir)/config/depcomp
 am__depfiles_maybe = depfiles
@@ -134,8 +135,8 @@ LTCOMPILE = $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) \
 CCLD = $(CC)
 LINK = $(LIBTOOL) --tag=CC --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
 	$(AM_LDFLAGS) $(LDFLAGS) -o $@
-SOURCES = $(libHPCisa_la_SOURCES)
-DIST_SOURCES = $(libHPCisa_la_SOURCES)
+SOURCES = $(libHPCprof_juicy_x_la_SOURCES)
+DIST_SOURCES = $(libHPCprof_juicy_x_la_SOURCES)
 ETAGS = etags
 CTAGS = ctags
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
@@ -331,18 +332,15 @@ HPC_LIBSUPPORT = $(top_builddir)/src/lib/support/libHPCsupport.la
 # Local settings
 #############################################################################
 MYSOURCES = \
-	AlphaISA.hpp AlphaISA.cpp \
-	IA64ISA.hpp IA64ISA.cpp \
-	ISA.hpp ISA.cpp \
-	ISATypes.hpp \
-	MipsISA.hpp MipsISA.cpp \
-	SparcISA.hpp SparcISA.cpp \
-	x86ISA.hpp x86ISA.cpp \
-	instructionSets/alpha.h \
-	instructionSets/mips.h
+	XercesSAX2.hpp XercesSAX2.cpp \
+	XercesErrorHandler.hpp XercesErrorHandler.cpp \
+	\
+	DocHandlerArgs.hpp \
+	PGMDocHandler.hpp PGMDocHandler.cpp \
+	PROFILEDocHandler.hpp PROFILEDocHandler.cpp
 
-MYCFLAGS = @HOST_CFLAGS@   $(HPC_IFLAGS) @GNUBINUTILS_IFLAGS@
-MYCXXFLAGS = @HOST_CXXFLAGS@ $(HPC_IFLAGS) @GNUBINUTILS_IFLAGS@
+MYCFLAGS = @HOST_CFLAGS@   $(HPC_IFLAGS)
+MYCXXFLAGS = @HOST_CXXFLAGS@ $(HPC_IFLAGS) @XERCES_IFLAGS@
 @IS_HOST_AR_FALSE@MYAR = $(AR) cru
 @IS_HOST_AR_TRUE@MYAR = @HOST_AR@
 MYLIBADD = @HOST_LIBTREPOSITORY@
@@ -351,12 +349,12 @@ MYCLEAN = @HOST_LIBTREPOSITORY@
 #############################################################################
 # Automake rules
 #############################################################################
-noinst_LTLIBRARIES = libHPCisa.la
-libHPCisa_la_SOURCES = $(MYSOURCES)
-libHPCisa_la_CFLAGS = $(MYCFLAGS)
-libHPCisa_la_CXXFLAGS = $(MYCXXFLAGS)
-libHPCisa_la_AR = $(MYAR)
-libHPCisa_la_LIBADD = $(MYLIBADD)
+noinst_LTLIBRARIES = libHPCprof-juicy-x.la
+libHPCprof_juicy_x_la_SOURCES = $(MYSOURCES)
+libHPCprof_juicy_x_la_CFLAGS = $(MYCFLAGS)
+libHPCprof_juicy_x_la_CXXFLAGS = $(MYCXXFLAGS)
+libHPCprof_juicy_x_la_AR = $(MYAR)
+libHPCprof_juicy_x_la_LIBADD = $(MYLIBADD)
 MOSTLYCLEANFILES = $(MYCLEAN)
 MYCPPFLAGS_CXX = $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) \
 	$(MYCXXFLAGS)
@@ -377,9 +375,9 @@ $(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/src/Makeinclude.conf
 	      exit 1;; \
 	  esac; \
 	done; \
-	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  src/lib/isa/Makefile'; \
+	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  src/lib/prof-juicy-x/Makefile'; \
 	cd $(top_srcdir) && \
-	  $(AUTOMAKE) --foreign  src/lib/isa/Makefile
+	  $(AUTOMAKE) --foreign  src/lib/prof-juicy-x/Makefile
 .PRECIOUS: Makefile
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	@case '$?' in \
@@ -406,8 +404,8 @@ clean-noinstLTLIBRARIES:
 	  echo "rm -f \"$${dir}/so_locations\""; \
 	  rm -f "$${dir}/so_locations"; \
 	done
-libHPCisa.la: $(libHPCisa_la_OBJECTS) $(libHPCisa_la_DEPENDENCIES) 
-	$(CXXLINK)  $(libHPCisa_la_LDFLAGS) $(libHPCisa_la_OBJECTS) $(libHPCisa_la_LIBADD) $(LIBS)
+libHPCprof-juicy-x.la: $(libHPCprof_juicy_x_la_OBJECTS) $(libHPCprof_juicy_x_la_DEPENDENCIES) 
+	$(CXXLINK)  $(libHPCprof_juicy_x_la_LDFLAGS) $(libHPCprof_juicy_x_la_OBJECTS) $(libHPCprof_juicy_x_la_LIBADD) $(LIBS)
 
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT)
@@ -415,12 +413,10 @@ mostlyclean-compile:
 distclean-compile:
 	-rm -f *.tab.c
 
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCisa_la-AlphaISA.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCisa_la-IA64ISA.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCisa_la-ISA.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCisa_la-MipsISA.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCisa_la-SparcISA.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCisa_la-x86ISA.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCprof_juicy_x_la-PGMDocHandler.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCprof_juicy_x_la-PROFILEDocHandler.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCprof_juicy_x_la-XercesErrorHandler.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libHPCprof_juicy_x_la-XercesSAX2.Plo@am__quote@
 
 .cpp.o:
 @am__fastdepCXX_TRUE@	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
@@ -443,47 +439,33 @@ distclean-compile:
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
 @am__fastdepCXX_FALSE@	$(LTCXXCOMPILE) -c -o $@ $<
 
-libHPCisa_la-AlphaISA.lo: AlphaISA.cpp
-@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCisa_la-AlphaISA.lo -MD -MP -MF "$(DEPDIR)/libHPCisa_la-AlphaISA.Tpo" -c -o libHPCisa_la-AlphaISA.lo `test -f 'AlphaISA.cpp' || echo '$(srcdir)/'`AlphaISA.cpp; \
-@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCisa_la-AlphaISA.Tpo" "$(DEPDIR)/libHPCisa_la-AlphaISA.Plo"; else rm -f "$(DEPDIR)/libHPCisa_la-AlphaISA.Tpo"; exit 1; fi
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='AlphaISA.cpp' object='libHPCisa_la-AlphaISA.lo' libtool=yes @AMDEPBACKSLASH@
+libHPCprof_juicy_x_la-XercesSAX2.lo: XercesSAX2.cpp
+@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCprof_juicy_x_la-XercesSAX2.lo -MD -MP -MF "$(DEPDIR)/libHPCprof_juicy_x_la-XercesSAX2.Tpo" -c -o libHPCprof_juicy_x_la-XercesSAX2.lo `test -f 'XercesSAX2.cpp' || echo '$(srcdir)/'`XercesSAX2.cpp; \
+@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCprof_juicy_x_la-XercesSAX2.Tpo" "$(DEPDIR)/libHPCprof_juicy_x_la-XercesSAX2.Plo"; else rm -f "$(DEPDIR)/libHPCprof_juicy_x_la-XercesSAX2.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='XercesSAX2.cpp' object='libHPCprof_juicy_x_la-XercesSAX2.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCisa_la-AlphaISA.lo `test -f 'AlphaISA.cpp' || echo '$(srcdir)/'`AlphaISA.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCprof_juicy_x_la-XercesSAX2.lo `test -f 'XercesSAX2.cpp' || echo '$(srcdir)/'`XercesSAX2.cpp
 
-libHPCisa_la-IA64ISA.lo: IA64ISA.cpp
-@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCisa_la-IA64ISA.lo -MD -MP -MF "$(DEPDIR)/libHPCisa_la-IA64ISA.Tpo" -c -o libHPCisa_la-IA64ISA.lo `test -f 'IA64ISA.cpp' || echo '$(srcdir)/'`IA64ISA.cpp; \
-@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCisa_la-IA64ISA.Tpo" "$(DEPDIR)/libHPCisa_la-IA64ISA.Plo"; else rm -f "$(DEPDIR)/libHPCisa_la-IA64ISA.Tpo"; exit 1; fi
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='IA64ISA.cpp' object='libHPCisa_la-IA64ISA.lo' libtool=yes @AMDEPBACKSLASH@
+libHPCprof_juicy_x_la-XercesErrorHandler.lo: XercesErrorHandler.cpp
+@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCprof_juicy_x_la-XercesErrorHandler.lo -MD -MP -MF "$(DEPDIR)/libHPCprof_juicy_x_la-XercesErrorHandler.Tpo" -c -o libHPCprof_juicy_x_la-XercesErrorHandler.lo `test -f 'XercesErrorHandler.cpp' || echo '$(srcdir)/'`XercesErrorHandler.cpp; \
+@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCprof_juicy_x_la-XercesErrorHandler.Tpo" "$(DEPDIR)/libHPCprof_juicy_x_la-XercesErrorHandler.Plo"; else rm -f "$(DEPDIR)/libHPCprof_juicy_x_la-XercesErrorHandler.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='XercesErrorHandler.cpp' object='libHPCprof_juicy_x_la-XercesErrorHandler.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCisa_la-IA64ISA.lo `test -f 'IA64ISA.cpp' || echo '$(srcdir)/'`IA64ISA.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCprof_juicy_x_la-XercesErrorHandler.lo `test -f 'XercesErrorHandler.cpp' || echo '$(srcdir)/'`XercesErrorHandler.cpp
 
-libHPCisa_la-ISA.lo: ISA.cpp
-@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCisa_la-ISA.lo -MD -MP -MF "$(DEPDIR)/libHPCisa_la-ISA.Tpo" -c -o libHPCisa_la-ISA.lo `test -f 'ISA.cpp' || echo '$(srcdir)/'`ISA.cpp; \
-@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCisa_la-ISA.Tpo" "$(DEPDIR)/libHPCisa_la-ISA.Plo"; else rm -f "$(DEPDIR)/libHPCisa_la-ISA.Tpo"; exit 1; fi
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='ISA.cpp' object='libHPCisa_la-ISA.lo' libtool=yes @AMDEPBACKSLASH@
+libHPCprof_juicy_x_la-PGMDocHandler.lo: PGMDocHandler.cpp
+@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCprof_juicy_x_la-PGMDocHandler.lo -MD -MP -MF "$(DEPDIR)/libHPCprof_juicy_x_la-PGMDocHandler.Tpo" -c -o libHPCprof_juicy_x_la-PGMDocHandler.lo `test -f 'PGMDocHandler.cpp' || echo '$(srcdir)/'`PGMDocHandler.cpp; \
+@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCprof_juicy_x_la-PGMDocHandler.Tpo" "$(DEPDIR)/libHPCprof_juicy_x_la-PGMDocHandler.Plo"; else rm -f "$(DEPDIR)/libHPCprof_juicy_x_la-PGMDocHandler.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='PGMDocHandler.cpp' object='libHPCprof_juicy_x_la-PGMDocHandler.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCisa_la-ISA.lo `test -f 'ISA.cpp' || echo '$(srcdir)/'`ISA.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCprof_juicy_x_la-PGMDocHandler.lo `test -f 'PGMDocHandler.cpp' || echo '$(srcdir)/'`PGMDocHandler.cpp
 
-libHPCisa_la-MipsISA.lo: MipsISA.cpp
-@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCisa_la-MipsISA.lo -MD -MP -MF "$(DEPDIR)/libHPCisa_la-MipsISA.Tpo" -c -o libHPCisa_la-MipsISA.lo `test -f 'MipsISA.cpp' || echo '$(srcdir)/'`MipsISA.cpp; \
-@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCisa_la-MipsISA.Tpo" "$(DEPDIR)/libHPCisa_la-MipsISA.Plo"; else rm -f "$(DEPDIR)/libHPCisa_la-MipsISA.Tpo"; exit 1; fi
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='MipsISA.cpp' object='libHPCisa_la-MipsISA.lo' libtool=yes @AMDEPBACKSLASH@
+libHPCprof_juicy_x_la-PROFILEDocHandler.lo: PROFILEDocHandler.cpp
+@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCprof_juicy_x_la-PROFILEDocHandler.lo -MD -MP -MF "$(DEPDIR)/libHPCprof_juicy_x_la-PROFILEDocHandler.Tpo" -c -o libHPCprof_juicy_x_la-PROFILEDocHandler.lo `test -f 'PROFILEDocHandler.cpp' || echo '$(srcdir)/'`PROFILEDocHandler.cpp; \
+@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCprof_juicy_x_la-PROFILEDocHandler.Tpo" "$(DEPDIR)/libHPCprof_juicy_x_la-PROFILEDocHandler.Plo"; else rm -f "$(DEPDIR)/libHPCprof_juicy_x_la-PROFILEDocHandler.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='PROFILEDocHandler.cpp' object='libHPCprof_juicy_x_la-PROFILEDocHandler.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCisa_la-MipsISA.lo `test -f 'MipsISA.cpp' || echo '$(srcdir)/'`MipsISA.cpp
-
-libHPCisa_la-SparcISA.lo: SparcISA.cpp
-@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCisa_la-SparcISA.lo -MD -MP -MF "$(DEPDIR)/libHPCisa_la-SparcISA.Tpo" -c -o libHPCisa_la-SparcISA.lo `test -f 'SparcISA.cpp' || echo '$(srcdir)/'`SparcISA.cpp; \
-@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCisa_la-SparcISA.Tpo" "$(DEPDIR)/libHPCisa_la-SparcISA.Plo"; else rm -f "$(DEPDIR)/libHPCisa_la-SparcISA.Tpo"; exit 1; fi
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='SparcISA.cpp' object='libHPCisa_la-SparcISA.lo' libtool=yes @AMDEPBACKSLASH@
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCisa_la-SparcISA.lo `test -f 'SparcISA.cpp' || echo '$(srcdir)/'`SparcISA.cpp
-
-libHPCisa_la-x86ISA.lo: x86ISA.cpp
-@am__fastdepCXX_TRUE@	if $(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -MT libHPCisa_la-x86ISA.lo -MD -MP -MF "$(DEPDIR)/libHPCisa_la-x86ISA.Tpo" -c -o libHPCisa_la-x86ISA.lo `test -f 'x86ISA.cpp' || echo '$(srcdir)/'`x86ISA.cpp; \
-@am__fastdepCXX_TRUE@	then mv -f "$(DEPDIR)/libHPCisa_la-x86ISA.Tpo" "$(DEPDIR)/libHPCisa_la-x86ISA.Plo"; else rm -f "$(DEPDIR)/libHPCisa_la-x86ISA.Tpo"; exit 1; fi
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='x86ISA.cpp' object='libHPCisa_la-x86ISA.lo' libtool=yes @AMDEPBACKSLASH@
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCisa_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCisa_la-x86ISA.lo `test -f 'x86ISA.cpp' || echo '$(srcdir)/'`x86ISA.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libHPCprof_juicy_x_la_CXXFLAGS) $(CXXFLAGS) -c -o libHPCprof_juicy_x_la-PROFILEDocHandler.lo `test -f 'PROFILEDocHandler.cpp' || echo '$(srcdir)/'`PROFILEDocHandler.cpp
 
 mostlyclean-libtool:
 	-rm -f *.lo
