Update xerces to version 3.1.1.  This version builds both shared and static libraries.  Seems to drop right in.

diff --git a/externals/xerces/configure b/externals/xerces/configure
--- a/externals/xerces/configure
+++ b/externals/xerces/configure
@@ -6,23 +6,25 @@
 #
 
 PKG_NAME=xerces
-build_dir=xerces-c-src_2_8_0/src/xercesc
+src=xerces-c-3.1.1
 
 . ../build-utils/configure.inc
 pre_configure
 prefix="$xerces_prefix"
 
-set -- -m inmem -n socket -r pthread -t native "$@" # add -s for static
-set -- -c "$CC" -x "$CXX" "$@"
-set -- -P "$prefix" -p "$xerces_platform" "$@"
-if test -n "${is_cross_compile}" ; then
-    set -- -C --host="${host}" "$@"
+set --  \
+    CC="$CC"  CFLAGS="$CFLAGS"  \
+    CXX="$CXX"  CXXFLAGS="$CXXFLAGS"  \
+    --prefix="$prefix"  "$@"
+if test -n "$is_cross_compile" ; then
+    set -- --host="$host" "$@"
 fi
 
-cd "$build_dir" || die "unable to cd: $build_dir"
+make_work_dir
+cd work || die "unable to cd: work"
 
-echo runConfigure "$@"
-./runConfigure "$@"
+echo configure "$@"
+../${src}/configure "$@"
 test $? -eq 0 || die "configure failed"
 
 post_configure
