Add the hpcrun/link plugins! Also change the system to use pkg-config variables, and to use pkg-config for the --plugin argument as well.

diff --git a/src/tool/hpcrun/scripts/hpclink.meson.in b/src/tool/hpcrun/scripts/hpclink.meson.in
--- a/src/tool/hpcrun/scripts/hpclink.meson.in
+++ b/src/tool/hpcrun/scripts/hpclink.meson.in
@@ -229,32 +229,42 @@ do
 	-io | --io )
 	    PKG_CONFIG_PATH="${pc_dir}" pkg-config --exists hpcrun_io_wrap || die "unable to find: hpcrun_io_wrap"
 	    extra_hpc_libs="$extra_hpc_libs hpcrun_io_wrap"
-	    extra_wrap_names="$extra_wrap_names read write fread fwrite"
-	    undef_names="$undef_names fwrite"
+	    extra_wrap_names="$extra_wrap_names \
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=wrapnames hpcrun_io_wrap | tr ':' ' ')"
+	    undef_names="$undef_names \
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=undefnames hpcrun_io_wrap | tr ':' ' ')"
 	    shift
 	    ;;
 	-ga | --ga )
 	    PKG_CONFIG_PATH="${pc_dir}" pkg-config --exists hpcrun_ga_wrap || die "unable to find: hpcrun_ga_wrap"
 	    extra_hpc_libs="$extra_hpc_libs hpcrun_ga_wrap"
 	    extra_wrap_names="$extra_wrap_names \
-                pnga_create pnga_create_handle \
-                pnga_get pnga_put pnga_acc \
-                pnga_nbget pnga_nbput pnga_nbacc pnga_nbwait \
-                pnga_brdcst pnga_gop pnga_sync"
-	    undef_names="$undef_names pnga_create"
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=wrapnames hpcrun_ga_wrap | tr ':' ' ')"
+	    undef_names="$undef_names \
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=undefnames hpcrun_ga_wrap | tr ':' ' ')"
 	    shift
 	    ;;
 	-memleak | --memleak )
 	    PKG_CONFIG_PATH="${pc_dir}" pkg-config --exists hpcrun_memleak_wrap || die "unable to find: hpcrun_memleak_wrap"
 	    extra_hpc_libs="$extra_hpc_libs hpcrun_memleak_wrap"
-	    extra_wrap_names="$extra_wrap_names posix_memalign memalign valloc"
-	    extra_wrap_names="$extra_wrap_names calloc free malloc realloc"
-	    undef_names="$undef_names malloc"
+	    extra_wrap_names="$extra_wrap_names \
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=wrapnames hpcrun_memleak_wrap | tr ':' ' ')"
+	    undef_names="$undef_names \
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=undefnames hpcrun_memleak_wrap | tr ':' ' ')"
 	    shift
 	    ;;
 	-plugin | --plugin )
 	    test "x$2" != x || die "missing argument for --plugin"
-	    my_plugin_list="${my_plugin_list} $2"
+	    plugin_lib="hpcrun_$2_wrap"
+	    if ! PKG_CONFIG_PATH="${pc_dir}" pkg-config --exists "$plugin_lib"; then
+		plugin_lib="$2"
+		PKG_CONFIG_PATH="${pc_dir}" pkg-config --exists "$plugin_lib" || die "unable to find: $2"
+	    fi
+	    extra_hpc_libs="$extra_hpc_libs $plugin_lib"
+	    extra_wrap_names="$extra_wrap_names \
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=wrapnames "$plugin_lib" | tr ':' ' ')"
+	    undef_names="$undef_names \
+	      $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --variable=undefnames "$plugin_lib" | tr ':' ' ')"
 	    shift ; shift
 	    ;;
 	-u | --undefined )
@@ -302,42 +312,6 @@ case "$alt_fnbounds" in
 esac
 
 test -x "$hpcfnbounds" || die "unable to execute hpcfnbounds: $hpcfnbounds"
-
-#
-# Add plugin files: hpclink --plugin name
-# Plugin name and hpclink_files can be absolute path or relative to
-# the plugins directory.
-#
-extra_plugin_files=
-for plugin in $my_plugin_list
-do
-    $verb "plugin: $plugin"
-    case "$plugin" in
-	/* ) conf_file="$plugin" ;;
-	* )  conf_file="${plugin_dir}/${plugin}" ;;
-    esac
-    my_plugin_dir=`dirname "$conf_file"`
-    test -f "$conf_file" || die "missing plugin config file: $conf_file"
-    file "$conf_file" | grep text >/dev/null 2>&1
-    test $? -eq 0 || die "bad plugin config file: $conf_file"
-    hpclink_files=
-    hpclink_wrap_names=
-    hpclink_undefined_names=
-    . "$conf_file"
-    for file in $hpclink_files ; do
-	case "$file" in
-	    /* ) abs_file="$file" ;;
-	    * )  abs_file="${my_plugin_dir}/${file}" ;;
-	esac
-	test -f "$abs_file" || die "missing plugin file: $abs_file"
-	$verb "plugin file: $abs_file"
-	extra_plugin_files="$extra_plugin_files $abs_file"
-    done
-    $verb "plugin wrap names: $hpclink_wrap_names"
-    $verb "plugin undefined names: $hpclink_undefined_names"
-    extra_wrap_names="$extra_wrap_names $hpclink_wrap_names"
-    undef_names="$undef_names $hpclink_undefined_names"
-done
 
 #
 # Must have a compiler command and at least one argument.
@@ -430,7 +404,7 @@ set -- "$@" "${nm_addrs}.o"
 PKG_CONFIG_PATH="${pc_dir}" pkg-config --exists hpcrun_wrap || die "unable to find: hpcrun_wrap"
 PKG_CONFIG_PATH="${pc_dir}" pkg-config --exists monitor_wrap || die "unable to find: monitor_wrap"
 set -- "$@" $(PKG_CONFIG_PATH="${pc_dir}" pkg-config --libs hpcrun_wrap $extra_hpc_libs monitor_wrap hpcrun_deps)
-set -- "$@" $lib_args $extra_plugin_files $appl_libs
+set -- "$@" $lib_args $appl_libs
 
 #------------------------------------------------------------
 # Step 3 -- Link with dummy nm file.
