Adapt fnbounds to the upcoming Dyninst 10.2.0 release with openmp support in Symtab.
 1. configure tests if libsymtabAPI.so is compiled with openmp.

 2. Makefile adds -fopenmp as needed.

 3. hpcrun and hpcfnbounds support a '-js num' option to specify the
 number of openmp threads for symtab in fnbounds (default 1).

 4. rip out the option processing in the fnbounds launch script and
 handle all options in the binary.  we haven't used this and it hasn't
 worked right for years.

To use threads in hpcfnbounds, use a recent dyninst pre-10.2.0 from
master and export HPCFNBOUNDS_NUM_THREADS=num, or else use
'hpcrun -js num ...'.  OMP_NUM_THREADS applies to the application.

Although this commit supports threads in fnbounds, the latest Symtab
will use threads whether we support it or not.  The real purpose is to
prevent fnbounds from consuming every available thread per process.

diff --git a/src/tool/hpcrun/scripts/hpcrun.in b/src/tool/hpcrun/scripts/hpcrun.in
--- a/src/tool/hpcrun/scripts/hpcrun.in
+++ b/src/tool/hpcrun/scripts/hpcrun.in
@@ -146,7 +146,11 @@ Options: Profiling (Defaults shown in curly brackets {})
                        processes.  For each process, enable measurement
                        (of all threads) with probability <frac>; <frac> is a
                        real number (0.10) or a fraction (1/10) between 0 and 1.
-  
+
+  -js <num>, --jobs-symtab <num>
+                       Use <num> openmp threads for Symtab in hpcfnbounds,
+                       if Symtab supports openmp (default 1).
+
   -m, --merge-threads  Merge non-overlapped threads into one virtual thread.
                        This option is to reduce the number of generated
                        profile and trace files as each thread generates its own
@@ -223,7 +227,7 @@ do
 	    shift
 	    ;;
 
-  -ck | --control-knob )
+	-ck | --control-knob )
 	    arg_ok "$1" || die "missing argument for $arg"
 	    export HPCRUN_CONTROL_KNOBS="$HPCRUN_CONTROL_KNOBS $1"
 	    shift
@@ -273,7 +277,7 @@ do
 	# --------------------------------------------------
 
  	-c | --count )
- 	 	export HPCRUN_PERF_COUNT="$1"
+ 	    export HPCRUN_PERF_COUNT="$1"
 	    shift
 	    ;;
 
@@ -281,6 +285,13 @@ do
 
 	-t | --trace )
 	    export HPCRUN_TRACE=1
+	    ;;
+
+	# --------------------------------------------------
+
+	-js | --jobs-symtab )
+	    export HPCFNBOUNDS_NUM_THREADS="$1"
+	    shift
 	    ;;
 
 	# --------------------------------------------------
@@ -304,13 +315,13 @@ do
 	    export HPCRUN_RETAIN_RECURSION=1
 	    ;;
 
-  # --------------------------------------------------
+	# --------------------------------------------------
 
-  -m | --merge-threads )
-      arg_ok "$1" || die "missing argument for $arg"
-      export HPCRUN_MERGE_THREADS="$1"
-      shift
-      ;;
+	-m | --merge-threads )
+	    arg_ok "$1" || die "missing argument for $arg"
+	    export HPCRUN_MERGE_THREADS="$1"
+	    shift
+	    ;;
       
 	# --------------------------------------------------
 
