Add a way to sample a fraction of the mallocs with the MEMLEAK sample source.  For programs with a very high rate of mallocs, this can cut the memleak overhead significantly at the cost of not monitoring every malloc.

diff --git a/src/tool/hpcrun/scripts/hpcrun.in b/src/tool/hpcrun/scripts/hpcrun.in
--- a/src/tool/hpcrun/scripts/hpcrun.in
+++ b/src/tool/hpcrun/scripts/hpcrun.in
@@ -235,6 +235,12 @@ do
 	    export MONITOR_DEBUG=1
 	    ;;
 
+	-mp | --memleak-prob )
+	    arg_ok "$1" || die "missing argument for $arg"
+	    export HPCRUN_MEMLEAK_PROB="$1"
+	    shift
+	    ;;
+
 	-ms | --memsize )
 	    arg_ok "$1" || die "missing argument for $arg"
 	    export HPCRUN_MEMSIZE="$1"
