Opencl instrumentation fixgtpinbindings (#360)
* fix opencl wrappers so they don't always try to measure

opencl wrappers assumed that -e gpu=opencl was provided
as a command line argument. if that wasn't done, the
opencl wrappers would call through uninitialized function
pointers.

if any opencl wrapper is used, make sure that all of the
function pointers to the wrapped functions are bound
before any is used.

* don't link with gtpin library by default

linking with the gtpin library causes gtpin to be loaded
when libhpcrun.so is loaded even for programs that don't
use an intel gpu.

* bind to gtpin dynamically

use dlsym to find gtpin functions rather than calling them
directly

have hpcrun set gtpin library path and GTPIN_DEBUG=1 to
work with LD_AUDIT

* inform device finalizers why process is exiting

for anything other than a normal exit, opencl
finalizers shouldn't spin waiting for pending operations
to complete since they may never complete.

* gtpin refinements

add missing initialization for a function pointer to gtpin-interface.c
add return stubs to gtpin-instrumentation.c for sanity checks

* add support for replacing dlmopen with dlopen for gtpin

* Fix hpcrun Makefile.am unmatched endif

* Use ENABLE_IGC to control the visibility of igc related functions

* changed to hpcrun for audit + dlmopen

add arguments --namespace-multiple, --namespace-single
collapse to a single namespace when using gtpin or --namespace-single
improve help messages for hpcrun: separate options used only to avert failure
export rtld_audit_mesg from configure; use it in hpcrun to understand auditor configuration

Makefile.in changes resulting from configure.ac in next commit

* Makefile.in changes due to previous commit

* remove tabs in in hpcrun help message

* clean up interfaces for dynamic symbol binding

* fix type errors related to gpu-operation-item pending_operations

* Use GTPIN_ENABLE macro to control extra compilation flags

* modify hpcrun script to ensure no :: added to LD_LIBRARY_PATH

A zero-length prefix in PATH and LD_LIBRARY_PATH is a legacy
feature that indicates the current working directory.

In this commit, avoid adding any :: to LD_LIBRARY_PATH by
not adding items like :${path1}: when ${path1} might be
empty.

Co-authored-by: Jokeren <robinho364@gmail.com>

diff --git a/src/tool/hpcrun/scripts/hpcrun.in b/src/tool/hpcrun/scripts/hpcrun.in
--- a/src/tool/hpcrun/scripts/hpcrun.in
+++ b/src/tool/hpcrun/scripts/hpcrun.in
@@ -20,6 +20,7 @@ libmonitor_dir='@LIBMONITOR_RUN_DIR@'
 papi_libdir='@OPT_PAPI_LIBPATH@'
 perfmon_libdir='@PERFMON_LIB@'
 roctracer_lib_path='@OPT_ROCM@/roctracer/lib'
+gtpin_lib_path='@OPT_GTPIN_LIBDIR@'
 # gotcha_lib_path='@GOTCHA_LIBDIR@'
 
 prog_name=hpcrun
@@ -45,6 +46,7 @@ case "$libmonitor_dir" in
     * ) libmonitor_dir="${HPCTOOLKIT}/${libmonitor_dir}" ;;
 esac
 case "$papi_libdir" in
+    '' ) ;;
     /* ) ;;
     * ) papi_libdir="${HPCTOOLKIT}/${papi_libdir}" ;;
 esac
@@ -52,7 +54,7 @@ esac
 #
 # Once hpcrun_dir is completely set, set
 #
-ext_dir="$hpcrun_dir"/ext-libs
+ext_libdir="$hpcrun_dir"/ext-libs
 
 #------------------------------------------------------------
 # Usage Message
@@ -95,7 +97,7 @@ the directory:
 where <jobid> is a job launcher id that associated with the execution, if any.
 
 hpcrun enables a user to abort a process and write the partial profiling
-data to disk by sending a signal such as SIGINT (often bound to Ctrl-C).  
+data to disk by sending a signal such as SIGINT (often bound to Ctrl-C).
 This can be extremely useful on long-running or misbehaving applications.
 
 Options: Informational
@@ -105,26 +107,26 @@ Options: Informational
 
 Options: Profiling (Defaults shown in curly brackets {})
   -e <event>[@<howoften>], --event <event>[@<howoften>]
-                      event  may  be an architecture-independent hardware or 
-                      software event supported by Linux perf, a native hardware 
-                      counter event, a hardware counter event supported by the 
-                      PAPI library, a Linux  system timer (CPUTIME and REALTIME), 
-                      or the operating system interval timer WALLCLOCK.  This option 
-                      may be given multiple times to profile several events at once.  
-                      If the value for <howoften> is a number, it will be 
-                      interpreted as a sample period. For Linux perf events, one 
-                      may specify a sampling frequency for 'howoften' by writing f 
-                      before a number.  For instance, to sample an event 100 times 
-                      per second,  specify  <howoften>  as '@f100'. For Linux perf 
-                      events, if no value for <howoften> is specified, hpcrun 
-                      will monitor the event using frequency-based sampling at 300 
+                      event  may  be an architecture-independent hardware or
+                      software event supported by Linux perf, a native hardware
+                      counter event, a hardware counter event supported by the
+                      PAPI library, a Linux  system timer (CPUTIME and REALTIME),
+                      or the operating system interval timer WALLCLOCK.  This option
+                      may be given multiple times to profile several events at once.
+                      If the value for <howoften> is a number, it will be
+                      interpreted as a sample period. For Linux perf events, one
+                      may specify a sampling frequency for 'howoften' by writing f
+                      before a number.  For instance, to sample an event 100 times
+                      per second,  specify  <howoften>  as '@f100'. For Linux perf
+                      events, if no value for <howoften> is specified, hpcrun
+                      will monitor the event using frequency-based sampling at 300
                       samples/second.
 
   -c, --count <howoften>
-                      Only  available  for  events  managed  by Linux perf. This 
-                      option specifies a default value for how often to sample. The 
-                      value for <howoften> may be a number that will be used as a 
-                      default event period or an f followed by a number, e.g. f100, 
+                      Only  available  for  events  managed  by Linux perf. This
+                      option specifies a default value for how often to sample. The
+                      value for <howoften> may be a number that will be used as a
+                      default event period or an f followed by a number, e.g. f100,
                       to specify a default sampling frequency in samples/second.
 
   -t, --trace          Generate a call path trace in addition to a call
@@ -136,13 +138,6 @@ Options: Profiling (Defaults shown in curly brackets {})
   -ds, --delay-sampling
                        Delay starting sampling until the application calls
                        hpctoolkit_sampling_start().
-
-  --disable-gprof      Override and disable gprof instrumentation  This option
-                       is only useful when using hpcrun to add HPCToolkit's
-                       measurement subsystem to a dynamically-linked application 
-                       that has been compiled with -pg. One can't measure 
-                       performance with HPCToolkit when gprof instrumentation 
-                       is active in the same execution.
 
   -f <frac>, -fp <frac>, --process-fraction <frac>
                        Measure only a fraction <frac> of the execution's
@@ -163,7 +158,7 @@ Options: Profiling (Defaults shown in curly brackets {})
                        profile and trace files as each thread generates its own
                        profile and trace data. The options are:
                        0 : do not merge non-overlapped threads
-                       1 : merge non-overlapped threads (default) 
+                       1 : merge non-overlapped threads (default)
 
   -o <outpath>, --output <outpath>
                        Directory for output data.
@@ -175,7 +170,7 @@ Options: Profiling (Defaults shown in curly brackets {})
 
   -r, --retain-recursion
                        Normally, hpcrun will collapse (simple) recursive call chains
-                       to save space and analysis time. This option disables that 
+                       to save space and analysis time. This option disables that
                        behavior: all elements of a recursive call chain will be recorded
                        NOTE: If the user employs the RETCNT sample source, then this
                              option is enabled: RETCNT implies *all* elements of
@@ -184,10 +179,36 @@ Options: Profiling (Defaults shown in curly brackets {})
   -nu, --no-unwind     Disable unwinding
                        Generates a flat profile (leaf instructions) only
 
+Options to consider only when hpcrun causes an application to fail:
+
+  --namespace-single   dlmopen may load a shared library into an alternate
+                       namespace.  Use of dlmopen to create multiple namespaces
+                       can cause an application to crash when using glibc < 2.32
+                       (see NOTES). This option asks HPCToolkit to load all
+                       shared libraries within the application namespace, which
+                       might help avoid a crash.  (Default when performing
+                       instruction-level measurements of Intel GPU binaries.)
+
+  --namespace-multiple dlmopen may load a shared library into an alternate
+                       namespace. Force HPCToolkit to allow dlmopen to create
+                       alternate namespaces.  (Default unless performing
+                       instruction-level measurements of Intel GPU binaries.)
+
+  --disable-gprof      Override and disable gprof instrumentation  This option
+                       is only useful when using hpcrun to add HPCToolkit's
+                       measurement subsystem to a dynamically-linked application
+                       that has been compiled with -pg. One can't measure
+                       performance with HPCToolkit when gprof instrumentation
+                       is active in the same execution.
+
+
 NOTES:
 * hpcrun uses preloaded shared libraries to initiate profiling.  For this
   reason, it cannot be used to profile setuid programs.
-* hpcrun may not be able to profile programs that themselves use preloading.
+* By default, hpcrun use LD_AUDIT to monitor an application's use of dynamic
+  libraries. Use of LD_AUDIT will cause dlmopen to fail for glibc < 2.32. Intel's
+  GTPin library for instrumentation of Intel GPU binaries uses dlmopen.
+
 
 EOF
     exit 0
@@ -200,7 +221,7 @@ EOF
 @launch_early_options@
 
 # Return success (0) if $1 is not empty and not the next option.
-arg_ok()
+non_empty()
 {
     case "x$1" in
 	x | x-* ) return 1 ;;
@@ -212,8 +233,19 @@ arg_ok()
 # LD_PRELOAD should be delayed until we launch the program, but the
 # others can be set now.
 
+namespace_gtpin=multiple
 preload_list=
-roctracer_lib=
+roctracer_libdir=
+gtpin_libdir=
+namespace_default=multiple
+namespace_multiple=
+namespace_single=
+
+if test @rtld_audit_mesg@ = yes ; then
+  namespace_gtpin=single
+fi
+
+
 HPCRUN_DEBUG_FLAGS=
 HPCRUN_EVENT_LIST=
 HPCRUN_CONTROL_KNOBS=
@@ -232,7 +264,7 @@ do
 	    ;;
 
 	-dd | --dynamic-debug )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_DEBUG_FLAGS="$HPCRUN_DEBUG_FLAGS $1"
 	    shift
 	    ;;
@@ -242,7 +274,7 @@ do
 	    ;;
 
 	-ck | --control-knob )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_CONTROL_KNOBS="$HPCRUN_CONTROL_KNOBS $1"
 	    shift
 	    ;;
@@ -258,7 +290,7 @@ do
 	# --------------------------------------------------
 
 	-a | --agent )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_OPT_LUSH_AGENTS="$1"
 	    shift
 	    ;;
@@ -266,7 +298,7 @@ do
 	# --------------------------------------------------
 
 	-e | --event )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    case "$1" in
 	        GA* )      preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_ga.so" ;;
 		IO* )      preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_io.so" ;;
@@ -275,8 +307,15 @@ do
 		PTHREAD_WAIT* ) preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_pthread.so" ;;
 		CPU_GPU_IDLE* ) preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_gpu.so" ;;
 		MPI* )     preload_list="${preload_list} ${hpcrun_dir}/libhpcrun_mpi.so" ;;
-		gpu=amd) roctracer_lib="${roctracer_lib_path}"
+		gpu=amd) roctracer_libdir="${roctracer_lib_path}"
 			 export HIP_ENABLE_DEFERRED_LOADING=0;;
+
+		gpu=opencl,inst) gtpin_libdir="${gtpin_lib_path}"
+		    namespace_default=$namespace_gtpin ;;
+
+		gpu=level0,inst) gtpin_libdir="${gtpin_lib_path}"
+		    namespace_default=$namespace_gtpin ;;
+
 	    esac
 	    case "$HPCRUN_EVENT_LIST" in
 		'' ) HPCRUN_EVENT_LIST="$1" ;;
@@ -323,7 +362,7 @@ do
 	# --------------------------------------------------
 
 	-o | --output )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_OUT_PATH="$1"
 	    shift
 	    ;;
@@ -340,6 +379,21 @@ do
 	    export HPCRUN_OMP_SERIAL_ONLY=1
 	    ;;
 
+
+	# --------------------------------------------------
+
+	--namespace-multiple )
+	    non_empty "$namespace_single" && die "can't use both --namespace-single and --namespace-multiple"
+	    namespace_multiple=yes
+	    ;;
+
+	# --------------------------------------------------
+
+	--namespace-single )
+	    non_empty "$namespace_multiple" && die "can't use both --namespace-single and --namespace-multiple"
+	    namespace_single=yes
+	    ;;
+
 	# --------------------------------------------------
 
 	-r | --retain-recursion )
@@ -349,21 +403,21 @@ do
 	# --------------------------------------------------
 
 	-m | --merge-threads )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_MERGE_THREADS="$1"
 	    shift
 	    ;;
-      
+
 	# --------------------------------------------------
 
 	-lm | --low-memsize )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_LOW_MEMSIZE="$1"
 	    shift
 	    ;;
 
 	-ms | --memsize )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_MEMSIZE="$1"
 	    shift
 	    ;;
@@ -371,13 +425,13 @@ do
 	# --------------------------------------------------
 
 	-f | -fp | --process-fraction )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_PROCESS_FRACTION="$1"
 	    shift
 	    ;;
 
 	-mp | --memleak-prob )
-	    arg_ok "$1" || die "missing argument for $arg"
+	    non_empty "$1" || die "missing argument for $arg"
 	    export HPCRUN_MEMLEAK_PROB="$1"
 	    shift
 	    ;;
@@ -420,6 +474,15 @@ if test -z "$1" ; then
 	die "no command to profile"
     fi
 fi
+
+
+# collapse namespaces, if necessary
+if test "$namespace_multiple"x = x ; then
+  if test $namespace_default = single || test "$namespace_single"x != x ; then
+    preload_list="${hpcrun_dir}/libhpcrun_dlmopen.so ${preload_list}"
+  fi
+fi
+
 
 #------------------------------------------------------------
 # Pre-Launch Sanity Checks
@@ -502,8 +565,23 @@ fi
 # Enable core files.
 ulimit -S -c unlimited >/dev/null 2>&1
 
-# laks 2016.10.06: add perfmon directory
-hpc_ld_library_path="${hpcrun_dir}:${papi_libdir}:${ext_dir}:${perfmon_libdir}:${roctracer_lib}"
+
+#------------------------------------------------------------
+# assemble hpc_ld_library_path without any empty entries
+#------------------------------------------------------------
+
+hpc_ld_library_path="${hpcrun_dir}"
+hpc_ld_library_path="${hpc_ld_library_path}${papi_libdir:+:${papi_libdir}}"
+hpc_ld_library_path="${hpc_ld_library_path}${ext_libdir:+:${ext_libdir}}"
+hpc_ld_library_path="${hpc_ld_library_path}${perfmon_libdir:+:${perfmon_libdir}}"
+hpc_ld_library_path="${hpc_ld_library_path}${roctracer_libdir:+:${roctracer_libdir}}"
+hpc_ld_library_path="${hpc_ld_library_path}${gtpin_libdir:+:${gtpin_libdir}}"
+
+
+#------------------------------------------------------------
+# assemble preload list
+#------------------------------------------------------------
+
 preload_list="${libmonitor_dir}/libmonitor.so ${preload_list}"
 preload_list="${hpcrun_dir}/libhpcrun.so ${preload_list}"
 
