Change the test for GNU compilers to 'CC --version' instead of looking for the __GNUC__ symbol.  The Intel icc compiler defines __GNUC__ and so was fooling the test.

diff --git a/externals/configure b/externals/configure
--- a/externals/configure
+++ b/externals/configure
@@ -3397,14 +3397,22 @@ if test "x$build" != "x$host" ; then
    is_cross_compile=${host}
 fi
 
-# Warn if not using gcc, but give a pass if you're trying to cross
-# compile.  Some packages don't build well without gcc.  This is not a
-# great test, since autoconf identifies Intel icc as gcc, and binutils
-# barfs on icc. (grrr)
+# Warn if not using GNU gcc and g++.  Some packages don't build
+# cleanly without gcc.  For example, binutils fails with icc.
 
-ext_warn_non_gcc=no
-if test "x$GCC" != xyes && test "x$is_cross_compile" = x ; then
-    ext_warn_non_gcc=yes
+warn_non_gcc=no
+$CC --version 2>&1 | grep GCC >/dev/null 2>&1
+if test $? -ne 0 ; then
+    warn_non_gcc=yes
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Not using the GNU C compiler." >&5
+$as_echo "$as_me: WARNING: Not using the GNU C compiler." >&2;}
+fi
+
+$CXX --version 2>&1 | grep GCC >/dev/null 2>&1
+if test $? -ne 0 ; then
+    warn_non_gcc=yes
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Not using the GNU C++ compiler." >&5
+$as_echo "$as_me: WARNING: Not using the GNU C++ compiler." >&2;}
 fi
 
 #------------------------------------------------------------
@@ -5824,6 +5832,20 @@ $as_echo "$as_me: ------------------" >&6;}
 $as_echo "$as_me: Externals summary" >&6;}
 { $as_echo "$as_me:${as_lineno-$LINENO}: ------------------" >&5
 $as_echo "$as_me: ------------------" >&6;}
+
+if test "$warn_non_gcc" = yes ; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Not using the GNU C or C++ compiler." >&5
+$as_echo "$as_me: WARNING: Not using the GNU C or C++ compiler." >&2;}
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: This is not necessarily an error, but some packages may not" >&5
+$as_echo "$as_me: WARNING: This is not necessarily an error, but some packages may not" >&2;}
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: compile cleanly without gcc or g++.  If the build fails, try" >&5
+$as_echo "$as_me: WARNING: compile cleanly without gcc or g++.  If the build fails, try" >&2;}
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: using GNU gcc and g++ before reporting an error." >&5
+$as_echo "$as_me: WARNING: using GNU gcc and g++ before reporting an error." >&2;}
+    { $as_echo "$as_me:${as_lineno-$LINENO}: --------------------------" >&5
+$as_echo "$as_me: --------------------------" >&6;}
+fi
+
 { $as_echo "$as_me:${as_lineno-$LINENO}: svn revision: $svn_revision" >&5
 $as_echo "$as_me: svn revision: $svn_revision" >&6;}
 { $as_echo "$as_me:${as_lineno-$LINENO}: prefix: $prefix ($enable_subdirs_mesg)" >&5
@@ -5878,13 +5900,3 @@ files that it needs to the real install directory.  Thus, the prefix
 option is not used for this build." >&2;}
 fi
 
-if test "$ext_warn_non_gcc" = yes ; then
-    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Not using the GNU C compiler.
-This is not necessarily an error, but some of these packages may not
-compile cleanly without gcc or g++.  If the build fails, try using the
-default values of CC and CXX before reporting an error." >&5
-$as_echo "$as_me: WARNING: Not using the GNU C compiler.
-This is not necessarily an error, but some of these packages may not
-compile cleanly without gcc or g++.  If the build fails, try using the
-default values of CC and CXX before reporting an error." >&2;}
-fi
