Update symtabAPI to 7.0.1 and drop support for 2.1. Turn on 7.0 as the default.

diff --git a/externals/symtabAPI/patches/patch-libelf b/externals/symtabAPI/patches/patch-libelf
--- a/externals/symtabAPI/patches/patch-libelf
+++ b/externals/symtabAPI/patches/patch-libelf
@@ -1,40 +1,339 @@
-Change #include <libelf.h> to <libelf/libelf.h>.
-This matches the usage that libelf uses for itself.
+Change #include <libelf.h> to "libelf/libelf.h" in source files and
+rework configure to test for this style.  This is how libelf installs
+itself natively.
 
-diff -Naurb symtabAPI.orig/src/core/symtabAPI/src/Elf_X.h symtabAPI/src/core/symtabAPI/src/Elf_X.h
---- symtabAPI.orig/src/core/symtabAPI/src/Elf_X.h	2010-06-25 17:17:47.000000000 -0500
-+++ symtabAPI/src/core/symtabAPI/src/Elf_X.h	2010-06-25 17:24:01.000000000 -0500
+diff -Naurb symtabAPI.orig/src/dyninst/common/h/Elf_X.h symtabAPI/src/dyninst/common/h/Elf_X.h
+--- symtabAPI.orig/src/dyninst/common/h/Elf_X.h	2011-04-07 14:51:49.000000000 -0500
++++ symtabAPI/src/dyninst/common/h/Elf_X.h	2011-04-12 16:37:20.000000000 -0500
 @@ -33,7 +33,7 @@
  #define __ELF_X_H__
  
  #include <elf.h>
 -#include <libelf.h>
-+#include <libelf/libelf.h>
++#include "libelf/libelf.h"
  #include "common/h/headers.h"
  
- // Wrappers to allow word-independant use of libelf routines.
-diff -Naurb symtabAPI.orig/src/core/symtabAPI/src/Object-elf.h symtabAPI/src/core/symtabAPI/src/Object-elf.h
---- symtabAPI.orig/src/core/symtabAPI/src/Object-elf.h	2008-03-05 15:41:50.000000000 -0600
-+++ symtabAPI/src/core/symtabAPI/src/Object-elf.h	2010-06-25 17:24:53.000000000 -0500
-@@ -44,11 +44,10 @@
- #include "common/h/headers.h"
- #include "common/h/Types.h"
+ // Forward declarations
+diff -Naurb symtabAPI.orig/src/dyninst/configure symtabAPI/src/dyninst/configure
+--- symtabAPI.orig/src/dyninst/configure	2011-04-12 16:23:01.000000000 -0500
++++ symtabAPI/src/dyninst/configure	2011-04-12 16:27:22.000000000 -0500
+@@ -3134,19 +3134,18 @@
+ done
+ 
+ 
+-as_ac_Header=`echo "ac_cv_header_$LIBELF_INC_DIR/libelf.h" | $as_tr_sh`
+-if eval "test \"\${$as_ac_Header+set}\" = set"; then
+-  echo "$as_me:$LINENO: checking for $LIBELF_INC_DIR/libelf.h" >&5
+-echo $ECHO_N "checking for $LIBELF_INC_DIR/libelf.h... $ECHO_C" >&6
+-if eval "test \"\${$as_ac_Header+set}\" = set"; then
++if test "${ac_cv_header_libelf_libelf_h+set}" = set; then
++  echo "$as_me:$LINENO: checking for libelf/libelf.h" >&5
++echo $ECHO_N "checking for libelf/libelf.h... $ECHO_C" >&6
++if test "${ac_cv_header_libelf_libelf_h+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ fi
+-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
++echo "$as_me:$LINENO: result: $ac_cv_header_libelf_libelf_h" >&5
++echo "${ECHO_T}$ac_cv_header_libelf_libelf_h" >&6
+ else
+   # Is the header compilable?
+-echo "$as_me:$LINENO: checking $LIBELF_INC_DIR/libelf.h usability" >&5
+-echo $ECHO_N "checking $LIBELF_INC_DIR/libelf.h usability... $ECHO_C" >&6
++echo "$as_me:$LINENO: checking libelf/libelf.h usability" >&5
++echo $ECHO_N "checking libelf/libelf.h usability... $ECHO_C" >&6
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -3154,7 +3153,7 @@
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+ $ac_includes_default
+-#include <$LIBELF_INC_DIR/libelf.h>
++#include <libelf/libelf.h>
+ _ACEOF
+ rm -f conftest.$ac_objext
+ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+@@ -3190,15 +3189,15 @@
+ echo "${ECHO_T}$ac_header_compiler" >&6
+ 
+ # Is the header present?
+-echo "$as_me:$LINENO: checking $LIBELF_INC_DIR/libelf.h presence" >&5
+-echo $ECHO_N "checking $LIBELF_INC_DIR/libelf.h presence... $ECHO_C" >&6
++echo "$as_me:$LINENO: checking libelf/libelf.h presence" >&5
++echo $ECHO_N "checking libelf/libelf.h presence... $ECHO_C" >&6
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+ cat confdefs.h >>conftest.$ac_ext
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+-#include <$LIBELF_INC_DIR/libelf.h>
++#include <libelf/libelf.h>
+ _ACEOF
+ if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+@@ -3232,25 +3231,25 @@
+ # So?  What about this header?
+ case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+   yes:no: )
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h: accepted by the compiler, rejected by the preprocessor!" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h: proceeding with the compiler's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h: accepted by the compiler, rejected by the preprocessor!" >&5
++echo "$as_me: WARNING: libelf/libelf.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: libelf/libelf.h: proceeding with the compiler's result" >&2;}
+     ac_header_preproc=yes
+     ;;
+   no:yes:* )
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h: present but cannot be compiled" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h: present but cannot be compiled" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h: proceeding with the preprocessor's result" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf.h: in the future, the compiler will take precedence" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h: present but cannot be compiled" >&5
++echo "$as_me: WARNING: libelf/libelf.h: present but cannot be compiled" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h:     check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: libelf/libelf.h:     check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h: see the Autoconf documentation" >&5
++echo "$as_me: WARNING: libelf/libelf.h: see the Autoconf documentation" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h:     section \"Present But Cannot Be Compiled\"" >&5
++echo "$as_me: WARNING: libelf/libelf.h:     section \"Present But Cannot Be Compiled\"" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h: proceeding with the preprocessor's result" >&5
++echo "$as_me: WARNING: libelf/libelf.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libelf/libelf.h: in the future, the compiler will take precedence" >&5
++echo "$as_me: WARNING: libelf/libelf.h: in the future, the compiler will take precedence" >&2;}
+     (
+       cat <<\_ASBOX
+ ## ------------------------------- ##
+@@ -3261,173 +3260,27 @@
+       sed "s/^/$as_me: WARNING:     /" >&2
+     ;;
+ esac
+-echo "$as_me:$LINENO: checking for $LIBELF_INC_DIR/libelf.h" >&5
+-echo $ECHO_N "checking for $LIBELF_INC_DIR/libelf.h... $ECHO_C" >&6
+-if eval "test \"\${$as_ac_Header+set}\" = set"; then
++echo "$as_me:$LINENO: checking for libelf/libelf.h" >&5
++echo $ECHO_N "checking for libelf/libelf.h... $ECHO_C" >&6
++if test "${ac_cv_header_libelf_libelf_h+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  eval "$as_ac_Header=\$ac_header_preproc"
++  ac_cv_header_libelf_libelf_h=$ac_header_preproc
+ fi
+-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
++echo "$as_me:$LINENO: result: $ac_cv_header_libelf_libelf_h" >&5
++echo "${ECHO_T}$ac_cv_header_libelf_libelf_h" >&6
+ 
+ fi
+-if test `eval echo '${'$as_ac_Header'}'` = yes; then
++if test $ac_cv_header_libelf_libelf_h = yes; then
+   { echo "$as_me:$LINENO: ELF include directory: $LIBELF_INC_DIR" >&5
+ echo "$as_me: ELF include directory: $LIBELF_INC_DIR" >&6;}
+ else
+-  CXXFLAGS="$CXXFLAGS -I$LIBELF_INC_DIR/libelf";
+-         CPPFLAGS="$CPPFLAGS -I$LIBELF_INC_DIR/libelf";
+-         as_ac_Header=`echo "ac_cv_header_$LIBELF_INC_DIR/libelf/libelf.h" | $as_tr_sh`
+-if eval "test \"\${$as_ac_Header+set}\" = set"; then
+-  echo "$as_me:$LINENO: checking for $LIBELF_INC_DIR/libelf/libelf.h" >&5
+-echo $ECHO_N "checking for $LIBELF_INC_DIR/libelf/libelf.h... $ECHO_C" >&6
+-if eval "test \"\${$as_ac_Header+set}\" = set"; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-fi
+-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+-else
+-  # Is the header compilable?
+-echo "$as_me:$LINENO: checking $LIBELF_INC_DIR/libelf/libelf.h usability" >&5
+-echo $ECHO_N "checking $LIBELF_INC_DIR/libelf/libelf.h usability... $ECHO_C" >&6
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-$ac_includes_default
+-#include <$LIBELF_INC_DIR/libelf/libelf.h>
+-_ACEOF
+-rm -f conftest.$ac_objext
+-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+-  (eval $ac_compile) 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } &&
+-	 { ac_try='test -z "$ac_cxx_werror_flag"
+-			 || test ! -s conftest.err'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; } &&
+-	 { ac_try='test -s conftest.$ac_objext'
+-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+-  (eval $ac_try) 2>&5
+-  ac_status=$?
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; }; then
+-  ac_header_compiler=yes
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-ac_header_compiler=no
+-fi
+-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+-echo "${ECHO_T}$ac_header_compiler" >&6
+-
+-# Is the header present?
+-echo "$as_me:$LINENO: checking $LIBELF_INC_DIR/libelf/libelf.h presence" >&5
+-echo $ECHO_N "checking $LIBELF_INC_DIR/libelf/libelf.h presence... $ECHO_C" >&6
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-#include <$LIBELF_INC_DIR/libelf/libelf.h>
+-_ACEOF
+-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } >/dev/null; then
+-  if test -s conftest.err; then
+-    ac_cpp_err=$ac_cxx_preproc_warn_flag
+-    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+-  else
+-    ac_cpp_err=
+-  fi
+-else
+-  ac_cpp_err=yes
+-fi
+-if test -z "$ac_cpp_err"; then
+-  ac_header_preproc=yes
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-  ac_header_preproc=no
+-fi
+-rm -f conftest.err conftest.$ac_ext
+-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+-echo "${ECHO_T}$ac_header_preproc" >&6
+-
+-# So?  What about this header?
+-case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+-  yes:no: )
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: accepted by the compiler, rejected by the preprocessor!" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: proceeding with the compiler's result" >&2;}
+-    ac_header_preproc=yes
+-    ;;
+-  no:yes:* )
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: present but cannot be compiled" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: present but cannot be compiled" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: proceeding with the preprocessor's result" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: $LIBELF_INC_DIR/libelf/libelf.h: in the future, the compiler will take precedence" >&2;}
+-    (
+-      cat <<\_ASBOX
+-## ------------------------------- ##
+-## Report this to bugs@dyninst.org ##
+-## ------------------------------- ##
+-_ASBOX
+-    ) |
+-      sed "s/^/$as_me: WARNING:     /" >&2
+-    ;;
+-esac
+-echo "$as_me:$LINENO: checking for $LIBELF_INC_DIR/libelf/libelf.h" >&5
+-echo $ECHO_N "checking for $LIBELF_INC_DIR/libelf/libelf.h... $ECHO_C" >&6
+-if eval "test \"\${$as_ac_Header+set}\" = set"; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  eval "$as_ac_Header=\$ac_header_preproc"
+-fi
+-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+-
+-fi
+-if test `eval echo '${'$as_ac_Header'}'` = yes; then
+-  LIBELF_INC_DIR+="/libelf";{ echo "$as_me:$LINENO: ELF include directory: $LIBELF_INC_DIR" >&5
+-echo "$as_me: ELF include directory: $LIBELF_INC_DIR" >&6;}
+-else
+   { { echo "$as_me:$LINENO: error: couldn't find libelf.h" >&5
+ echo "$as_me: error: couldn't find libelf.h" >&2;}
+    { (exit 1); exit 1; }; }
+ fi
+ 
+ 
+-fi
+-
+ 
+    CXXFLAGS=$CXXFLAGS_HOLD;
+    CPPFLAGS=$CPPFLAGS_HOLD;
+diff -Naurb symtabAPI.orig/src/dyninst/configure.in symtabAPI/src/dyninst/configure.in
+--- symtabAPI.orig/src/dyninst/configure.in	2011-04-12 16:23:01.000000000 -0500
++++ symtabAPI/src/dyninst/configure.in	2011-04-12 16:26:44.000000000 -0500
+@@ -105,12 +105,10 @@
+    CPPFLAGS_HOLD=$CPPFLAGS;
+    CPPFLAGS="$CPPFLAGS -I$LIBELF_INC_DIR";
+                         
+-   AC_CHECK_HEADER([$LIBELF_INC_DIR/libelf.h], [AC_MSG_NOTICE(ELF include directory: $LIBELF_INC_DIR)],
+-        [CXXFLAGS="$CXXFLAGS -I$LIBELF_INC_DIR/libelf";
+-         CPPFLAGS="$CPPFLAGS -I$LIBELF_INC_DIR/libelf";
+-         AC_CHECK_HEADER([$LIBELF_INC_DIR/libelf/libelf.h],
+-                         [LIBELF_INC_DIR+="/libelf";AC_MSG_NOTICE(ELF include directory: $LIBELF_INC_DIR)],
+-                         [AC_ERROR(couldn't find libelf.h)])])
++   AC_CHECK_HEADER([libelf/libelf.h],
++	[AC_MSG_NOTICE(ELF include directory: $LIBELF_INC_DIR)],
++	[AC_ERROR(couldn't find libelf.h)])
++
+    CXXFLAGS=$CXXFLAGS_HOLD;
+    CPPFLAGS=$CPPFLAGS_HOLD;
+    PD_CHECK_LIB_DIR($LIBELF_LIB_DIR,[elf],[elf_memory])
+diff -Naurb symtabAPI.orig/src/dyninst/symtabAPI/src/Object-elf.h symtabAPI/src/dyninst/symtabAPI/src/Object-elf.h
+--- symtabAPI.orig/src/dyninst/symtabAPI/src/Object-elf.h	2011-04-07 14:52:22.000000000 -0500
++++ symtabAPI/src/dyninst/symtabAPI/src/Object-elf.h	2011-04-12 16:37:20.000000000 -0500
+@@ -56,7 +56,7 @@
+ 
+ 
  #include <elf.h>
 -#include <libelf.h>
-+#include <libelf/libelf.h>
++#include "libelf/libelf.h"
+ #include <string>
  
- #include "Elf_X.h"
+ #include "common/h/Elf_X.h"
+diff -Naurb symtabAPI.orig/src/dyninst/symtabAPI/src/parseDwarf.C symtabAPI/src/dyninst/symtabAPI/src/parseDwarf.C
+--- symtabAPI.orig/src/dyninst/symtabAPI/src/parseDwarf.C	2011-04-07 14:52:23.000000000 -0500
++++ symtabAPI/src/dyninst/symtabAPI/src/parseDwarf.C	2011-04-12 16:37:20.000000000 -0500
+@@ -31,7 +31,7 @@
+ #include <map>
  
--#include <libelf.h>
- #include <fcntl.h>
- #include <stdlib.h>
- #include <unistd.h>
-diff -Naurb symtabAPI.orig/src/core/symtabAPI/src/parseDwarf.C symtabAPI/src/core/symtabAPI/src/parseDwarf.C
---- symtabAPI.orig/src/core/symtabAPI/src/parseDwarf.C	2008-04-23 11:43:04.000000000 -0500
-+++ symtabAPI/src/core/symtabAPI/src/parseDwarf.C	2010-06-25 17:25:20.000000000 -0500
-@@ -30,7 +30,7 @@
-  */
- 			     
  #include "elf.h"
 -#include "libelf.h"
 +#include "libelf/libelf.h"
