Normalize a few variable names.

diff --git a/externals/binutils/build b/externals/binutils/build
--- a/externals/binutils/build
+++ b/externals/binutils/build
@@ -9,20 +9,20 @@
 # subdirs (see configure)
 
 PKG_NAME=binutils
-SRC=version-binutils-2.17/binutils-2.17
+src=version-binutils-2.17/binutils-2.17
 
 . ../build-utils/configure.inc
 pre_build
 
 cd work || die "unable to cd: work"
-WORK=`pwd`
+work_dir=`pwd`
 
 
 dirs="libiberty bfd opcodes binutils"
 for x in ${dirs}; do
     echo "=> ${x}/build"
-    cd ${WORK}/${x}
-    $MAKE || die "build in ${x} failed"
+    cd ${work_dir}/${x}
+    $MAKE || die "unable to build ${x}"
 done
 
 
diff --git a/externals/binutils/configure b/externals/binutils/configure
--- a/externals/binutils/configure
+++ b/externals/binutils/configure
@@ -6,7 +6,7 @@
 #
 
 PKG_NAME=binutils
-SRC=version-binutils-2.17/binutils-2.17
+src=version-binutils-2.17/binutils-2.17
 
 . ../build-utils/configure.inc
 pre_configure
@@ -25,11 +25,11 @@ fi
 
 make_work_dir
 cd work || die "unable to cd: work"
-WORK=`pwd`
+work_dir=`pwd`
 
 # NOTE: this must come after 'make_work_dir' or 'make_work_dir' breaks
-cd "../${SRC}" || die "unable to cd: ${SRC}"
-SRC=`pwd`
+cd "../${src}" || die "unable to cd: ${src}"
+src=`pwd`
 
 
 # The top-level configure for binutils 2.17 does *not* pass along
@@ -37,15 +37,15 @@ SRC=`pwd`
 # top-level configure, we configure for each subdir.
 
 #echo configure "$@"
-#../${SRC}/configure "$@"
+#../${src}/configure "$@"
 #test $? -eq 0 || die "configure failed"
 
 dirs="libiberty bfd opcodes binutils"
 for x in . ${dirs}; do
     echo "=> ${x}/configure $@"
-    mkdir -p ${WORK}/${x} || die "unable to mkdir: ${WORK}/${x}"
-    cd ${WORK}/${x}
-    ${SRC}/${x}/configure "$@"
+    mkdir -p ${work_dir}/${x} || die "unable to mkdir: ${work_dir}/${x}"
+    cd ${work_dir}/${x}
+    ${src}/${x}/configure "$@"
     test $? -eq 0 || die "configure in ${x} failed"
 done
 
diff --git a/externals/binutils/install b/externals/binutils/install
--- a/externals/binutils/install
+++ b/externals/binutils/install
@@ -6,17 +6,17 @@
 #
 
 PKG_NAME=binutils
-SRC=version-binutils-2.17/binutils-2.17
+src=version-binutils-2.17/binutils-2.17
 
 . ../build-utils/configure.inc
 pre_install
 
 cd work || die "unable to cd: work"
-WORK=`pwd`
+work_dir=`pwd`
 
 # NOTE: this must come after 'make_work_dir' or 'make_work_dir' breaks
-cd "../${SRC}" || die "unable to cd: ${SRC}"
-SRC=`pwd`
+cd "../${src}" || die "unable to cd: ${src}"
+src=`pwd`
 
 
 # NOTE: this is necessary only becuase we selectively build subdirs
@@ -24,8 +24,8 @@ SRC=`pwd`
 dirs="libiberty bfd opcodes binutils"
 for x in ${dirs}; do
     echo "=> ${x}/install"
-    cd ${WORK}/${x}
-    $MAKE install || die "install in ${x} failed"
+    cd ${work_dir}/${x}
+    $MAKE install || die "unable to install ${x}"
 done
 
 
@@ -33,9 +33,9 @@ done
 # Copy extra headers: demangle.h plus its dependencies
 #
 dir_to="${prefix}/include/"
-to_copy="${SRC}/include/demangle.h \
-         ${SRC}/include/libiberty.h \
-         ${SRC}/include/ansidecl.h"
+to_copy="${src}/include/demangle.h \
+         ${src}/include/libiberty.h \
+         ${src}/include/ansidecl.h"
 
 echo "=> cp ${to_copy}"
 
