* Basic support for cross-compiling.   - Top level configure:     1) detects and passes along 'build' and 'host'     2) sets a flag to indicate if we are cross-compiling   - Within the various subpackages, add the equivalent of --host=<> to     the configure line when cross-compiling.   - Note: for now we don't have to worry about 'old-monitor'
* Add "FIXME" notes where gcc is hard-coded as the compiler:
    It is dangerous to hardcode 'gcc'; e.g., it breaks cross-compiling.
    Rather, in the top-level configure, the compiler should be tested to
    see if it is GCC-compatible (GCC, Intel...) and if so left alone.  If
    not, then resort to the optionally specified GCC compiler, which
    defaults to 'gcc'.

diff --git a/externals/binutils/configure b/externals/binutils/configure
--- a/externals/binutils/configure
+++ b/externals/binutils/configure
@@ -6,23 +6,47 @@
 #
 
 PKG_NAME=binutils
-src=version-binutils-2.17/binutils-2.17
+SRC=version-binutils-2.17/binutils-2.17
 
 . ../build-utils/configure.inc
 pre_configure
+
+targets='mips64-sgi-irix6, alpha-*-linux-gnu, alpha-*-osf, sparc32-*-elf, sparc64-*-solaris2, i386-*-linux-gnu, x86_64-*-linux-gnu, ia64-*-linux-gnu, powerpc64-*-linux-gnu'
 
 CC="$CC"
 CFLAGS="$CFLAGS"
 set -- \
     --prefix="$prefix" \
-    --enable-targets='mips64-sgi-irix6, alpha-*-linux-gnu, alpha-*-osf, sparc32-*-elf, sparc64-*-solaris2, i386-*-linux-gnu, x86_64-*-linux-gnu, ia64-*-linux-gnu, powerpc64-*-linux-gnu' \
+    --enable-targets="${targets}" \
     "$@"
+if test -n "${is_cross_compile}" ; then
+    set -- --host="${host}" "$@"
+fi
 
 make_work_dir
 cd work || die "unable to cd: work"
+WORK=`pwd`
 
-echo configure "$@"
-../${src}/configure "$@"
-test $? -eq 0 || die "configure failed"
+# NOTE: this must come after 'make_work_dir' or 'make_work_dir' breaks
+cd "../${SRC}" || die "unable to cd: ${SRC}"
+SRC=`pwd`
+
+
+# The top-level configure for binutils 2.17 does *not* pass along
+# --host to its sub-configures.  Erg!  So instead of just doing one
+# top-level configure, we configure for each subdir.
+
+#echo configure "$@"
+#../${SRC}/configure "$@"
+#test $? -eq 0 || die "configure failed"
+
+for x in . ${BINUTILS_DIRS}; do
+    echo "=> ${x}/configure $@"
+    mkdir -p ${WORK}/${x} || die "unable to mkdir: ${WORK}/${x}"
+    cd ${WORK}/${x}
+    ${SRC}/${x}/configure "$@"
+    test $? -eq 0 || die "configure in ${x} failed"
+done
+
 
 post_configure
diff --git a/externals/binutils/install b/externals/binutils/install
--- a/externals/binutils/install
+++ b/externals/binutils/install
@@ -6,24 +6,37 @@
 #
 
 PKG_NAME=binutils
-src=version-binutils-2.17/binutils-2.17
+SRC=version-binutils-2.17/binutils-2.17
 
 . ../build-utils/configure.inc
 pre_install
 
-cd "$src" || die "unable to cd: $src"
-src_dir=`pwd`
+cd work || die "unable to cd: work"
+WORK=`pwd`
+
+# NOTE: this must come after 'make_work_dir' or 'make_work_dir' breaks
+cd "../${SRC}" || die "unable to cd: ${SRC}"
+SRC=`pwd`
+
+
+for x in ${BINUTILS_DIRS}; do
+    echo "=> ${x}/install $@"
+    cd ${WORK}/${x}
+    $MAKE install || die "install in ${x} failed"
+done
+
 
 #
 # Copy extra headers: demangle.h plus its dependencies
 #
-dir_from=${src_dir}
 dir_to="${prefix}/include/"
-to_copy="include/demangle.h include/libiberty.h include/ansidecl.h"
+to_copy="${SRC}/include/demangle.h \
+         ${SRC}/include/libiberty.h \
+         ${SRC}/include/ansidecl.h"
 
 mkdir -p "${dir_to}" || die "unable to mkdir: ${dir_to}"
-for fnm in ${to_copy} ; do
-    cp "${dir_from}/${fnm}" ${dir_to} || die "cannot cp: ${dir_from}/${fnm}"
+for x in ${to_copy} ; do
+    cp ${x} ${dir_to} || die "unable to install: ${x}"
 done
 
 post_install
