Add -fPIC to our binutils build.  Some future packages (oprofile) want to use libbfd and libiberty in a shared library, so they need code compiled with -fPIC.  Libbfd and libiberty are common libraries, but they're not always built with PIC, so we just build them ourself.
Copy libiberty to its lib install directory.  Libiberty doesn't obey
the --libdir option and always installs into a multilib directory
(lib64 or lib32).  Copying it to lib simplifies finding it in other
packages.

diff --git a/externals/binutils/install b/externals/binutils/install
--- a/externals/binutils/install
+++ b/externals/binutils/install
@@ -44,4 +44,17 @@ for x in ${to_copy} ; do
     cp ${x} ${dir_to} || die "unable to install: ${x}"
 done
 
+#
+# Libiberty doesn't obey --libdir and always installs into a multilib
+# directory (lib64 or lib32).  Instead of hacking their Makefile, we
+# just copy the libraries.
+#
+cd "$prefix" || die "unable to cd: $prefix"
+for lib in lib64/lib* lib32/lib* ; do
+    if test -f "$lib" ; then
+	echo "cp $lib to lib"
+	cp -f "$lib" lib
+    fi
+done
+
 post_install
